### PR TITLE
network-libp2p: Filter valid addresses and fix discovery protocol

### LINKED ISSUE #2052: Peer Filtering
Especially for the WebClient there needs to be an option do forbid connections to insecure sockets.  
Otherwise the browser will flag the page as insecure.

Suggested filter rules:
- disable Insecure: true/false    ->disables ws://
- disable local IPs: true/false    ->disables all non public IPS

### PR DESCRIPTION
**Pull request by jsdanielh**
- Add several changes to filter valid addresses:
  - Remove the `identify` behaviour since it was returning peer addresses that sometimes are not valid such as secure websocket and IPs multiaddresses.
  - Let know the discovery behaviour about new listen addresses to mimic the `identify` behaviour and be able to discover more of our own addresses.
  - Add some filtering in the `PeerContactBook` such that the `discovery` and the `connection_pool` behaviours only return valid addresses (in `handle_pending_outbound_connection`).
  - Add a configuration knob in the network to allow only secure websocket connections and another one for allowing loopback addresses.
  - Only add an address for a peer in the DHT behaviour if it passes the validity filters such that it doesn't return invalid addresses when the swarm dials a peer.
  This fixes #2052.
- Fix the discovery protocol to always periodically send our own `PeerContact` (along with some of our contacts) which is updated frequently to avoid being aged.

## Pull request checklist

- [X] All tests pass. The project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

File: network-libp2p/src/discovery/handler.rs [hunk 1]
```diff
@@ -210,14 +210,18 @@ impl Handler {
 
     /// Get peer contacts from our contact book to send to this peer. The contacts are filtered according to the peer's
     /// protocols and service filters, they are limited to the number of peers specified by the peer.
-    fn get_peer_contacts(&self, peer_contact_book: &PeerContactBook) -> Vec<SignedPeerContact> {
-        let n = self.peer_list_limit.unwrap() as usize;
-
+    /// This list also includes our own contact which should be already filtered since we already have
+    /// connections to these peers.
+    fn get_peer_contacts(
+        &self,
```
Comment (hrxi) [inline network-libp2p/src/discovery/handler.rs:216]:
```suggestion
```
No longer necessary.

File: network-libp2p/src/config.rs [hunk 2]
```diff
@@ -58,7 +62,7 @@ impl Config {
                 let mut s = DefaultHasher::new();
                 message.topic.hash(&mut s);
                 message.data.hash(&mut s);
-                gossipsub::MessageId::from(s.finish().to_string())
+                gossipsub::MessageId::from(s.finish().to_be_bytes())
```
Comment (hrxi) [inline network-libp2p/src/config.rs]: Unrelated to this PR: `DefaultHasher` is not guaranteed to stay the same across Rust versions. Is it important that this is the same for all of the network? Couldn't immediately see that from the libp2p-gossipsub documentation: [`message_id_fn`](https://docs.rs/libp2p-gossipsub/0.46.1/libp2p_gossipsub/struct.ConfigBuilder.html#method.message_id_fn).

File: network-libp2p/src/discovery/peer_contacts.rs [hunk 3]
```diff
@@ -299,35 +316,43 @@ impl PeerContactBook {
...
+    pub fn insert_filtered(
+        &mut self,
+        contact: SignedPeerContact,
+        services_filter: Services,
+        only_secure_connections: bool,
+    ) {
         let info = PeerContactInfo::from(contact);
 
-        if self
+        // A peer is interested to us in two cases:
```
Comment (hrxi) [inline network-libp2p/src/discovery/peer_contacts.rs]:
```suggestion
        // A peer is interesting to us in two cases:
```
Looks like grammar but inverts the meaning.

File: network-libp2p/src/discovery/peer_contacts.rs [hunk 4]
```diff
@@ -299,35 +316,43 @@ impl PeerContactBook {
...
+        // - I'm configured as a validator, and the peer is also a validator, then that peer is interesting to me
+        //   regardless of the services that are provided by that peer.
+        // - There is a match in the services provided by the peer and our services
```
Comment (hrxi) [inline network-libp2p/src/discovery/peer_contacts.rs]:
```suggestion
        // - The services provided by the peer are a superset of the requested services.
```
It was unclear to me what a "match" was supposed to mean. Digging into the source code, it seems to mean "superset".

File: network-libp2p/src/discovery/peer_contacts.rs [hunk 5]
```diff
@@ -452,6 +491,69 @@ impl PeerContactBook {
...
+
+    /// Returns true if an address is a secure websocket connection.
+    /// If address doesn't have the websocket protocol, it will return `false`.
+    fn is_address_secure(address: &Multiaddr) -> bool {
+        address.into_iter().any(|p| matches!(p, Protocol::Wss(_)))
+    }
+
+    /// Returns true if an address is valid for dialing.
+    /// It performs basic checks against unsupported addresses.
+    pub fn is_address_valid(&self, address: &Multiaddr) -> bool {
```
Comment (hrxi) [inline network-libp2p/src/discovery/peer_contacts.rs]:
```suggestion
    pub fn is_address_dialable(&self, address: &Multiaddr) -> bool {
```
`valid` doesn't really tell me what this function does. Perhaps `dialable` would fit?

**Review by hrxi — COMMENTED** [review]
On a more general note, maybe we shouldn't call the wss connections "secure". As far as I know, all of our connections are secure. The difference to wss is that it has two layers that try to secure the connection, the transport and the libp2p protocol itself. I'm not sure what to call it, maybe "secure transport" or simply "secure websocket"? Maybe the latter.

File: network-libp2p/src/discovery/handler.rs (hunk 1 above)
Comment (jsdanielh) [reply network-libp2p/src/discovery/handler.rs:216]: It's still required for `self.service_filter`

File: network-libp2p/src/config.rs (hunk 2 above)
Comment (jsdanielh) [reply network-libp2p/src/config.rs]: Mmm, I'd say it is important. `libp2p-gossipsub` documentation is not very clear on this. But then, how would you propose to go since we can't use the inner `SipHashers` as they are deprecated?

**Review by hrxi — APPROVED** [review]
This looks good to me now. Does it require waiting for a testnet restart? @jsdanielh

File: network-libp2p/src/config.rs (hunk 2 above)
Comment (hrxi) [reply network-libp2p/src/config.rs]: We could use a standard cryptographic hash function, I guess.

**Comment by jsdanielh** [comment]
> This looks good to me now. Does it require waiting for a testnet restart? @jsdanielh

Mmm, I'd say that the change in gossipsub might need it

File: network-libp2p/src/discovery/handler.rs (hunk 1 above)
Comment (hrxi) [reply network-libp2p/src/discovery/handler.rs:216]: Oops.

File: network-libp2p/src/config.rs (hunk 2 above)
Comment (jsdanielh) [reply network-libp2p/src/config.rs]: I just changed it to use `sha256`

Comment (hrxi) [reply network-libp2p/src/config.rs]: Nice. :)
