### PR TITLE
Fixes bug in trie chunk

### LINKED ISSUE #1030: Panic in RPC server getValidatorByAddress with include_stakers = true when validator doesn't have stakers
### General information

- Library version(s): albatross latest commit
- Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the testnet? (Yes/No): Yes
- Related issues:

#### Expected behavior

> when having a validator that doesn't have any stakers it should be possible to request the validator with the stakers included. That should return an empty list of stakers.

#### Actual behavior

> The connection is closed abruptly. A panic was found in the logs that is probably caused by this:
```
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:  ERROR panic                | thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code': primitives/account/src/staking_contract/>
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:    0: <backtrace::capture::Backtrace as core::default::Default>::default
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:    1: log_panics::Config::install_panic_hook::{{closure}}
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:    2: std::panicking::rust_panic_with_hook
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:              at rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:    3: std::panicking::begin_panic_handler::{{closure}}
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:              at rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:586:13
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:    4: std::sys_common::backtrace::__rust_end_short_backtrace
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:              at rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:    5: rust_begin_unwind
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:              at rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:    6: core::panicking::panic_fmt
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:              at rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:    7: core::panicking::panic
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:              at rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:    8: nimiq_account::staking_contract::StakingContract::get_validator_stakers
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:    9: nimiq_rpc_server::dispatchers::blockchain::get_validator_by_address
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   11: <nimiq_rpc_server::dispatchers::blockchain::BlockchainDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   18: <warp::filter::and_then::AndThenFuture<T,F> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   19: <warp::filter::or::EitherFuture<T,U> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   20: <warp::filter::and::AndFuture<T,U> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   21: warp::route::set
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   22: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   23: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   24: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   25: <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   26: tokio::runtime::task::core::CoreStage<T>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   27: tokio::runtime::task::harness::Harness<T,S>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   28: std::thread::local::LocalKey<T>::with
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   29: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   30: tokio::runtime::scheduler::multi_thread::worker::Context::run
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   31: tokio::macros::scoped_tls::ScopedKey<T>::set
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   32: tokio::runtime::scheduler::multi_thread::worker::run
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   33: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   34: tokio::runtime::task::harness::Harness<T,S>::poll
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   35: tokio::runtime::blocking::pool::Inner::run
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   36: std::sys_common::backtrace::__rust_begin_short_backtrace
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   37: core::ops::function::FnOnce::call_once{{vtable.shim}}
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   38: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:              at rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:              at rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1951:9
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:       std::sys::unix::thread::Thread::new::thread_start
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:              at rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys/unix/thread.rs:108:17
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   39: <unknown>
Sep 14 17:43:45 ace-kimi nimiq-client[42056]:   40: <unknown>

```

### PR DESCRIPTION
**Pull request by viquezclaudio**
Fixes #1030
If a validator does not have any staker we return an empty list of stakers
The underlying issue was a problem in the get_trie_chunk when the size is 0

### CODE REVIEW

File: primitives/trie/src/trie.rs [hunk 1]
```diff
@@ -474,6 +474,10 @@ impl<A: Serialize + Deserialize + Clone> MerkleRadixTrie<A> {
     ) -> Vec<TrieNode<A>> {
         let mut chunk = Vec::new();
 
+        if size == 0_usize {
+            return vec![];
```
Comment (jsdanielh) [inline primitives/trie/src/trie.rs]:
```suggestion
            return chunk;
```
I think that's better since we would re-use the heap allocation. Or maybe we can move the chunk initialization to a line below?

**Comment by jsdanielh** [comment]
Also, include the issue reference in the commit body such that GH can link it

**Review by jsdanielh — APPROVED** [review]

**Review by jsdanielh — APPROVED** [review]
