### PR TITLE
Move rate limiting to swarm to fix the unprotected buffer

### LINKED ISSUE #2531: DoS vector on network
TODO Make buffer size configurable. unprotected buffer

Change rate limiting is to be applied before that, in a layer above to prevent this.

### PR DESCRIPTION
**Pull request by ii-cruz**
## What's in this pull request?
Moving rate limiting to swarm to fix the unprotected buffer of the network when handling a request.
Rate limit refactoring

## Pull request checklist
- [x] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

File: network-libp2p/src/network_types.rs [hunk 1]
```diff
@@ -248,8 +250,14 @@ pub(crate) struct TaskState {
...
         HashMap<InboundRequestId, ResponseChannel<Option<OutgoingResponse>>>,
     /// Senders for replying to requests per `RequestType` for request-response
-    pub(crate) receive_requests:
-        HashMap<RequestType, mpsc::Sender<(Bytes, InboundRequestId, PeerId)>>,
+    pub(crate) receive_requests: HashMap<
+        RequestType,
+        (
+            mpsc::Sender<(Bytes, InboundRequestId, PeerId)>,
+            u32,
+            Duration,
```
Comment (nibhar) [inline network-libp2p/src/network_types.rs]: I would prefer these be encapsulated into a named struct. It is used in a couple more places than just here. Not tagging all of them but just here.

File: network-libp2p/src/rate_limiting.rs [hunk 2]
```diff
@@ -142,10 +147,13 @@ impl RateLimit {
 
 // Network helpers for rate limiting
 
-pub(crate) fn is_under_the_rate_limits<Req: RequestCommon>(
-    peer_request_limits: Arc<Mutex<HashMap<PeerId, HashMap<u16, RateLimit>>>>,
+pub(crate) fn is_under_the_rate_limits(
```
Comment (nibhar) [inline network-libp2p/src/rate_limiting.rs]: Personally i would always go for `exceeds_rate_limit()`. Obviously that would inverse the return. however you already inverse the return from `increment_and_is_allowed` and then when calling this you invert again, so it should be fine,.

That being said doing all of this caller side would remove some of the clutter. The function has a bunch of parameters which are just used to init or retrieve the `RateLimit`. I would probably inline this making the function as a whole obsolete. Specifically as it is only used in a single spot.

**Review by nibhar — APPROVED** [review]
Generally I would like this to be more encapsulated. It looks correct to me and if necessary could go in like this, but I think it would be worth our while.

File: network-libp2p/src/network_types.rs [hunk 3]
```diff
@@ -248,8 +250,13 @@ pub(crate) struct TaskState {
     pub(crate) response_channels:
         HashMap<InboundRequestId, ResponseChannel<Option<OutgoingResponse>>>,
     /// Senders for replying to requests per `RequestType` for request-response
```
Comment (nibhar) [inline network-libp2p/src/network_types.rs]: This should probably reflect the update made.

File: network-libp2p/src/rate_limiting.rs [hunk 4]
```diff
@@ -141,114 +163,120 @@ impl RateLimit {
...
+                request_id,
+                peer_id,
+                request_type,
+                request_rate_limit_data.max_requests,
+                request_rate_limit_data.time_window,
+            );
+            return true;
+        }
+
+        false
```
Comment (nibhar) [inline network-libp2p/src/rate_limiting.rs]: I suggest keeping the debug log only. it is more informativ. Also I'd suggest to use tracing notation. Also if you log this callerside this can be replaced by 
```suggestion
        !requests_limit.increment_and_is_allowed(1)
```

**Review by nibhar — COMMENTED** [review]
Smaller notes but nothing major. I did not mention this in the review itself but add some rustdoc to functions and fields please.

File: network-interface/src/request/mod.rs [hunk 5]
```diff
@@ -143,7 +143,7 @@ pub trait RequestCommon:
 pub trait RequestSerialize: RequestCommon {
     /// Serializes a request.
     /// A serialized request is composed of:
-    /// - A varint for the Type ID of the request
+    /// - A variant for the Type ID of the request
```
Comment (hrxi) [inline network-interface/src/request/mod.rs]:
```suggestion
    /// - A variable sized integer for the Type ID of the request
```

`varint` as in "variable sized integer".

File: network-libp2p/src/swarm.rs [hunk 6]
```diff
@@ -702,53 +700,64 @@ fn handle_event(
...
-                                            None
-                                        }
-                                        None => None,
-                                    };
+
+                                    // Filter off sender if not alive.
+                                    let sender_data = state
+                                        .receive_requests
+                                        .get(&type_id)
+                                        .filter(|(sender, ..)| !sender.is_closed());
```
Comment (hrxi) [inline network-libp2p/src/swarm.rs:708]: This changes behavior. Previously, closed channels were removed from the map.

Is the behavior change intentional?

File: network-libp2p/src/swarm.rs [hunk 7]
```diff
@@ -1204,6 +1222,29 @@ pub(crate) fn verify_record(record: &Record) -> Option<DhtRecord> {
...
+        .is_err()
+    {
+        error!(
+            %request_id,
+            %peer_id,
+            %type_id,
+            "Could not send response {:?}", response
+        );
+    }
+}
```
Comment (hrxi) [inline network-libp2p/src/swarm.rs]: I feel like this function isn't carrying its weight. What was the reason for extracting the code into a function? Logging a message on error?

File: network-interface/src/request/mod.rs [hunk 8]
```diff
@@ -26,17 +26,17 @@ impl fmt::Display for RequestType {
...
     }
-    pub const fn request(type_id: u16) -> RequestType {
-        RequestType::new(type_id, true)
+    pub const fn request(type_id: u16) -> Self {
+        Self::new(type_id, true)
     }
-    pub const fn message(type_id: u16) -> RequestType {
-        RequestType::new(type_id, false)
+    pub const fn message(type_id: u16) -> Self {
+        Self::new(type_id, false)
```
Comment (hrxi) [inline network-interface/src/request/mod.rs:39]: This seems unrelated to the PR. Was it done unintentionally using automated refactoring?

**Review by hrxi — COMMENTED** [review]
Found a couple of potential issues.

File: network-interface/src/request/mod.rs (hunk 8 above)
Comment (ii-cruz) [reply network-interface/src/request/mod.rs:39]: I saw this issue on some other structs related to the rate-limiting and spotted it here too so I changed it as well

File: network-libp2p/src/swarm.rs (hunk 6 above)
Comment (ii-cruz) [reply network-libp2p/src/swarm.rs:708]: They are being removed later yes. I discussed it with JD. The code becomes more readable like this and the removal still happens later.

File: network-libp2p/src/swarm.rs (hunk 7 above)
Comment (ii-cruz) [reply network-libp2p/src/swarm.rs]: it's repeated in two places close by and simplified a bit the code there because there are so many If, else closes and nested scopes. Can change it back if you prefer, either way is fine imo

File: network-interface/src/request/mod.rs (hunk 5 above)
Comment (ii-cruz) [reply network-interface/src/request/mod.rs]: Thanks this was autocorrect mix-fixes

File: network-libp2p/src/swarm.rs (hunk 7 above)
Comment (ii-cruz) [reply network-libp2p/src/swarm.rs]: I removed the function and the response and respective error handling are done in the original places

**Comment by hrxi** [comment]
Rebasing to merge.
