### PR TITLE
Sync fixes

### LINKED ISSUE #1692: Head block stays behind syncing blocks
With version 0.12.0 the following situation consistently occurs when syncing a full node.

The observation is that  the head keeps hanging at block:
```
2023-07-11T08:56:12.974244000Z INFO  nimiq_client | Consensus status: false - Head: #43320- 27f124cc83b01e0463e9b0f993b61d2a2d65f7c36fffc25377294e623af46c2a block_number=43320 num_peers=15 status=false
2023-07-11T08:56:22.977049000Z INFO  nimiq_client | Consensus status: false - Head: #43320- 27f124cc83b01e0463e9b0f993b61d2a2d65f7c36fffc25377294e623af46c2a block_number=43320 num_peers=15 status=false
2023-07-11T08:56:32.974568000Z INFO  nimiq_client | Consensus status: false - Head: #43320- 27f124cc83b01e0463e9b0f993b61d2a2d65f7c36fffc25377294e623af46c2a block_number=43320 num_peers=15 status=false
```
Two minutes later
```
2023-07-11T08:58:02.981719000Z INFO  nimiq_client | Consensus status: false - Head: #43320- 27f124cc83b01e0463e9b0f993b61d2a2d65f7c36fffc25377294e623af46c2a block_number=43320 num_peers=15 status=false
```

But the `gossipsub` is way ahead:
```
2023-07-11T08:58:03.635607000Z DEBUG block_queue | Received block via gossipsub block=#48367:MI:50ce3316d8 <-- weird ordering
2023-07-11T08:58:04.063771000Z DEBUG block_queue | Received block via gossipsub block=#48366:MI:9d6906f0d5 <-- weird ordering
2023-07-11T08:58:04.063845000Z DEBUG block_queue | Received block via gossipsub block=#48367:MI:50ce3316d8 <-- weird ordering
2023-07-11T08:58:04.553403000Z DEBUG block_queue | Received block via gossipsub block=#48368:MI:25c32dc883
2023-07-11T08:58:05.653344000Z DEBUG block_queue | Received block via gossipsub block=#48369:MI:b9ec77e3bb
```
[full-sync-trace.log](https://github.com/nimiq/core-rs-albatross/files/12012776/full-sync-trace.log)

[full-sync-debug.log](https://github.com/nimiq/core-rs-albatross/files/12012718/full-sync-debug.log)

### PR DESCRIPTION
**Pull request by paberr**
## What's in this pull request?

- Fixing an off-by-one error in the verification of subsequent missing blocks requests.
- Re-requesting missing blocks after failures.
- The validator cached a flag for whether it can verify the transaction validity window and never updated it after being true. It now updates the flag when necessary.
- The calculation of the transaction validity window flag in the blockchain used a history store function, whose comment promised functionality that was not correctly implemented. @nibhar fixed this.
- The history store is using `u32`s in BE format specifically. There was a bug in the conversion that @sisou fixed.

This fixes #1692

## Pull request checklist

- [x] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

File: validator/src/validator.rs [hunk 1]
```diff
@@ -447,10 +447,12 @@ where
...
-        if !self.blockchain_state.can_enforce_validity_window
-            && self.blockchain.read().can_enforce_validity_window()
-        {
-            self.blockchain_state.can_enforce_validity_window = true;
+        let old_can_enforce_validity_window = self.blockchain_state.can_enforce_validity_window;
+        self.blockchain_state.can_enforce_validity_window =
+            self.blockchain.read().can_enforce_validity_window();
+
+        // Re-initialize validator when flag returns to true.
+        if !old_can_enforce_validity_window && self.blockchain_state.can_enforce_validity_window {
```
Comment (sisou) [inline validator/src/validator.rs:455]: I understand that caching `can_enforce_validity_window` was an optimization to not have to take a read lock on the blockchain and call a method for _every single block_. This change is now made so that the state can change from `true` at the launch of a fresh node back to `false` after sync, and then to `true` at the next election block.

Since the underlying condition of history-store-verifying-capability only changes on election blocks, maybe this state can still be cached during epochs, and the method still only called on epoch changes? That would correctly set it to `false` after sync, and back to `true` after the next election block.

I'm talking about full nodes here, but it would also apply to history nodes I believe.

Comment (paberr) [reply validator/src/validator.rs:455]: The flag can change only on macro blocks, so we improved the caching a bit.

**Review by ii-cruz — APPROVED** [review]
