### PR TITLE
Unsubscribe from subscribed address when transaction sending fails

### LINKED ISSUE #2456: Sending a transaction in `web-client` may not always unsubscribe from address
Link:		https://hackerone.com/reports/2491408  
Date:		2024-05-06 06:08:42 UTC  
By:		ryanrb  
Weakness:	Improper Resource Shutdown or Release  
  
Details:  
## Summary
In `web-client`, the method `send_transaction` will conditionally subscribe to an address based on specific conditions. Later in the method, the code ensures that this is cleaned up by unsubscribing from the address.

However, the actual method for sending a transaction uses the `?` operator, which means the operation can fail and return at that point—potentially causing the method to return after subscribing but before cleaning up the subscription.

### `consensus.send_transaction` is invoked with `?`

Project: `core-rs-albatross`
File reference: `web-client/src/client/lib.rs`
Line: 555
```
// Actually send the transaction
consensus.send_transaction(tx.native()).await?;
```

### The address is not unsubscribed from until line 574

Project: `core-rs-albatross`
File reference: `web-client/src/client/lib.rs`
Line: 578
```
// Unsubscribe from any address we subscribed to, without caring about the result
if let Some(address) = subscribed_address {
    let owned_consensus = consensus.clone();
    spawn_local(async move {
        let _ = owned_consensus
            .unsubscribe_from_addresses(vec![address], 1)
            .await;
    });
}
```

## Recommendation
Ensure that the address is unsubscribed from regardless of the success or failure of the outcome of `send_transaction`.

## References:
- [CWE-404](https://cwe.mitre.org/data/definitions/404.html)

## Impact
Depending on the amount of resources that subscribing to an address takes up, enough failed transactions could lead to resource exhaustion over time if nothing else cleans up the subscription.

### PR DESCRIPTION
**Pull request by sisou**
## What's in this pull request?

Unsubscribe from a previously subscribed address during tx-sending in the web-client. The address is subscribed to to get notified of the inclusion of the transaction in the chain, then unsubscribed at the end of the function. However, `send_transaction` itself can fail, in which case the subscription was not cleaned up.

@hrxi This currently is simply a duplication of the code found at the end of the function. Do you know a better way that only defines the logic once and then calls it from both places? Or another means to achieve this same result?

## Pull request checklist

- [x] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

File: web-client/src/client/lib.rs [hunk 1]
```diff
@@ -552,7 +552,21 @@ impl Client {
...
+                if let Some(address) = subscribed_address.clone() {
+                    let owned_consensus = consensus.clone();
+                    spawn_local(async move {
+                        let _ = owned_consensus
+                            .unsubscribe_from_addresses(vec![address], 1)
+                            .await;
+                    });
+                }
+                error
+            })?;
```
Comment (jsdanielh) [inline web-client/src/client/lib.rs]: Mmm, my $0.02 is that this is very error prone if we add more code between these lines and the place where we do the unsusbscribe below plus we are duplicating code. Maybe we could store this in a `struct` and implement `Drop` for this `struct`?

Comment (sisou) [reply web-client/src/client/lib.rs]: Oh, that's brilliant! 👍

Comment (hrxi) [reply web-client/src/client/lib.rs]: You can also see the pattern in 297a99a0b1531b703b6332132842410d51cf33f9.

Comment (sisou) [reply web-client/src/client/lib.rs]: Done.

File: web-client/src/client/lib.rs [hunk 2]
```diff
@@ -526,23 +528,47 @@ impl Client {
...
+                consensus
+                    .subscribe_to_addresses(vec![address.clone()], 1, None)
+                    .await?;
+                Ok(Self { address, consensus })
+            }
+        }
+        impl Drop for AddressSubscription {
+            fn drop(&mut self) {
+                let address = self.address.clone();
+                let consensus = self.consensus.clone();
```
Comment (nibhar) [inline web-client/src/client/lib.rs]: If these are both options you can `.take()` instead of `.clone()`. After they are moved the struct is droped and the `None` vanish, so there is no real need for the clones. Sadly as far as i know there is otherwise only `unsafe` ways of taking ownership here.

File: web-client/src/client/lib.rs [hunk 3]
```diff
@@ -569,15 +595,7 @@ impl Client {
...
-        // Unsubscribe from any address we subscribed to, without caring about the result
-        if let Some(address) = subscribed_address {
-            let owned_consensus = consensus.clone();
-            spawn_local(async move {
-                let _ = owned_consensus
-                    .unsubscribe_from_addresses(vec![address], 1)
-                    .await;
-            });
-        }
+        mem::drop(address_subscription);
```
Comment (nibhar) [inline web-client/src/client/lib.rs:603]: This will be implicitly executed as soon as the scope ends. Is there reason to do it earlier than that?

Comment (sisou) [reply web-client/src/client/lib.rs:603]: Otherwise Clippy complains the variable is never used and suggests to prefix it with an underscore. But then I fear it is compiled out?

File: web-client/src/client/lib.rs (hunk 2 above)
Comment (sisou) [reply web-client/src/client/lib.rs]: So is your suggestion to make them options?

File: web-client/src/client/lib.rs (hunk 3 above)
Comment (nibhar) [reply web-client/src/client/lib.rs:603]: The call to the drop implementation should make it not unused in the resulting representation. Thus even if underscored it should not get optimized away as it has observable behaviour attached to it (the drop impl). 

I am not entirely sure however if that is in fact true, so maybe keep it like it is.

File: web-client/src/client/lib.rs (hunk 2 above)
Comment (nibhar) [reply web-client/src/client/lib.rs]: Yes I would do that. It is a very small change and makes it more clean in my opinion.

File: web-client/src/client/lib.rs (hunk 3 above)
Comment (hrxi) [reply web-client/src/client/lib.rs:603]: > The call to the drop implementation should make it not unused in the resulting representation. Thus even if underscored it should not get optimized away as it has observable behaviour attached to it (the drop impl).
> 
> I am not entirely sure however if that is in fact true, so maybe keep it like it is.

Yes, if underscored, it doesn't get optimized away. Note that this is different from the name which only consists of an underscore `_` which means "immediately drop this".

I think the `mem::drop` is still fine, this way this PR doesn't change when the address is unsubscribed from in the happy case.

Comment (nibhar) [reply web-client/src/client/lib.rs:603]: Yeah I don't mind it either. More of a curiosity ask.

**Review by nibhar — APPROVED** [review]

**Review by jsdanielh — APPROVED** [review]
LGTM
