### PR TITLE
Remove unnecessary tokio::spawn

### LINKED ISSUE #2404: Browser light client cannot maintain connections
### General information

- Library version(s): v0.21.0
- Browser version(s): Chrome 123.0.6312.122
- Devices/Simulators/Machine affected: Desktop Linux
- Reproducible in the testnet? (Yes/No): yes
- Related issues: #

#### Expected behavior

Browser light clients can establish and hold connections with peers.

#### Actual behavior

Browser clients panic when connecting to the first peer (seed) with:

```
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime': /core-rs-albatross/network-interface/src/request/mod.rs:223
```

and can then no longer maintain connections, as peers disconnect after a few seconds because of response timeouts on their side.

#### Steps to reproduce

Either
- Open https://wallet.pos.nimiq-testnet.com in your browser.

or

- Compile the browser client locally (`./web-client/scripts/build.sh --only web --skip-types --skip-wasm-opt`) and serve the `web-client` folder, then go to http://localhost/example. If `seed1` is not up, change the seed node in `web-client/example/module.js` to a node that is up.

### PR DESCRIPTION
**Pull request by viquezclaudio**
- Unnecessary tokio spawn
- This is not compatible with web clients (WASM)

This could explain the failure mentioned in #2404 

Before [this change](https://github.com/nimiq/core-rs-albatross/commit/e7a0319fafaa10fcc7256061b89c2ad7e086c8c9) regular nodes didn't try to connect to web clients, because they were filtered: web clients do not provide any service to regular nodes. This can be observed in this [code](https://github.com/nimiq/core-rs-albatross/commit/e7a0319fafaa10fcc7256061b89c2ad7e086c8c9#diff-26b6d741d633ef4dcc78ac3d521f89ea1ead7110cad61ef8a987e23c5a12012cL528).

This means that before, **web clients were not responding to any of the consensus handlers**.

However, after the _handle incompatible peers_ commit, regular nodes can now perform head requests to web clients, which causes web clients to execute a `tokio::spawn`, which is not allowed (a special task executor is necessary in web environments).

This `tokio::spawn` seems unnecessary or superfluous (at least) according to the logic around it.

## Pull request checklist

- [X] All tests pass. The project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

File: network-interface/src/request/mod.rs [hunk 1]
```diff
@@ -220,24 +220,20 @@ pub fn request_handler<T: Send + Sync + Clone + 'static, Req: Handle<N, T>, N: N
                     let req_environment = req_environment.clone();
                     let network = Arc::clone(&network);
 
-                    tokio::spawn(async move {
```
Comment (sisou) [inline network-interface/src/request/mod.rs:223]: There's the same kind of spawn in the `message_handler` function below. Maybe that can be removed, too?

Comment (viquezclaudio) [reply network-interface/src/request/mod.rs:223]: That one looks unnecessary  too

**Review by sisou — APPROVED** [review]
Works! It might even have fixed the "closure invoked recursively or after being dropped" problem with libp2p's websocket-websys transport :astonished:

**Review by paberr — APPROVED** [review]

File: network-interface/src/request/mod.rs [hunk 2]
```diff
@@ -220,24 +220,20 @@ pub fn request_handler<T: Send + Sync + Clone + 'static, Req: Handle<N, T>, N: N
                     let req_environment = req_environment.clone();
                     let network = Arc::clone(&network);
```
Comment (hrxi) [inline network-interface/src/request/mod.rs]: These clones are likely unneeded if the `tokio::spawn` is removed below.

**Review by hrxi — COMMENTED** [review]
> This `tokio::spawn` seems unnecessary or superfluous (at least) according to the logic around it.

It doesn't seem entirely superfluous, it makes sure that each request cannot block the rest of the requests. If that's still wanted, then this change is incorrect.

**Comment by jsdanielh** [comment]
> > This `tokio::spawn` seems unnecessary or superfluous (at least) according to the logic around it.
> 
> It doesn't seem entirely superfluous, it makes sure that each request cannot block the rest of the requests. If that's still wanted, then this change is incorrect.

We will address this in a separate issue (#2434).
