### PR TITLE
Include Staking checks during mempool update.

### LINKED ISSUE #701: Panic: Failed to compute accounts hash during block production
When running the devnet docker scenario with:

- 1 seed node
- 5 validators
- 1 spammer
- 1 Albagen

The following panic was observed in validator 2 (seed2 in attached logs):

```
^[[36mseed2_1    |^[[0m ^[[2m2022-03-19T15:26:46.372387Z^[[0m ^[[31mERROR^[[0m ^[[2mpanic               ^[[0m | thread 'tokio-runtime-worker' panicked at 'Failed to compute accounts hash during block production: InsufficientFunds { needed: Coin(15322417), balance: Coin(3830604) }': block-production/src/lib.rs:84
^[[36mseed2_1    |^[[0m    0: log_panics::init::{{closure}}
^[[36mseed2_1    |^[[0m    1: std::panicking::rust_panic_with_hook
^[[36mseed2_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:610:17
^[[36mseed2_1    |^[[0m    2: std::panicking::begin_panic_handler::{{closure}}
^[[36mseed2_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:502:13
^[[36mseed2_1    |^[[0m    3: std::sys_common::backtrace::__rust_end_short_backtrace
^[[36mseed2_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/sys_common/backtrace.rs:139:18
^[[36mseed2_1    |^[[0m    4: rust_begin_unwind
^[[36mseed2_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:498:5
^[[36mseed2_1    |^[[0m    5: core::panicking::panic_fmt
^[[36mseed2_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/panicking.rs:106:14
^[[36mseed2_1    |^[[0m    6: core::result::unwrap_failed
^[[36mseed2_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/result.rs:1613:5
^[[36mseed2_1    |^[[0m    7: nimiq_block_production::BlockProducer::next_micro_block
^[[36mseed2_1    |^[[0m    8: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::produce_micro_block
^[[36mseed2_1    |^[[0m    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
^[[36mseed2_1    |^[[0m   10: futures_util::stream::stream::StreamExt::poll_next_unpin
^[[36mseed2_1    |^[[0m   11: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
```

And the following panic was observed in validator3 (seed3 in attached logs)

```
^[[36mseed3_1    |^[[0m ^[[2m2022-03-19T15:28:41.817697Z^[[0m ^[[31mERROR^[[0m ^[[2mpanic               ^[[0m | thread 'tokio-runtime-worker' panicked at 'Failed to compute accounts hash during block production: NonExistentAddress { address: Address("20e611f2b035ef8cbfd8cfb575706ef34858f128") }': block-production/src/lib.rs:84
^[[36mseed3_1    |^[[0m    0: log_panics::init::{{closure}}
^[[36mseed3_1    |^[[0m    1: std::panicking::rust_panic_with_hook
^[[36mseed3_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:610:17
^[[36mseed3_1    |^[[0m    2: std::panicking::begin_panic_handler::{{closure}}
^[[36mseed3_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:502:13
^[[36mseed3_1    |^[[0m    3: std::sys_common::backtrace::__rust_end_short_backtrace
^[[36mseed3_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/sys_common/backtrace.rs:139:18
^[[36mseed3_1    |^[[0m    4: rust_begin_unwind
^[[36mseed3_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/panicking.rs:498:5
^[[36mseed3_1    |^[[0m    5: core::panicking::panic_fmt
^[[36mseed3_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/panicking.rs:106:14
^[[36mseed3_1    |^[[0m    6: core::result::unwrap_failed
^[[36mseed3_1    |^[[0m              at /rustc/18bc4bee9710b181b440a472635150f0d6257713/library/core/src/result.rs:1613:5
^[[36mseed3_1    |^[[0m    7: nimiq_block_production::BlockProducer::next_micro_block
^[[36mseed3_1    |^[[0m    8: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::produce_micro_block
^[[36mseed3_1    |^[[0m    9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
^[[36mseed3_1    |^[[0m   10: futures_util::stream::stream::StreamExt::poll_next_unpin
^[[36mseed3_1    |^[[0m   11: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
```

Full logs:

[docker-devnet-logs.tar.gz](https://github.com/nimiq/core-rs-albatross/files/8309600/docker-devnet-logs.tar.gz)

### PR DESCRIPTION
**Pull request by viquezclaudio**
- The staking checks should be performed as well during blocks adoption, specially during adopted blocks:
  The staking state in the blockchain could have changed, causing some staking txns in the mempool
  become invalid.
- Fixes #701

### CODE REVIEW

File: mempool/tests/mod.rs [hunk 1]
```diff
@@ -13,8 +13,10 @@ use nimiq_bls::KeyPair as BlsKeyPair;
 use nimiq_database::volatile::VolatileEnvironment;
 use nimiq_genesis_builder::GenesisBuilder;
 use nimiq_hash::{Blake2bHash, Hash};
+
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]: No need to add this blank line

File: mempool/tests/mod.rs [hunk 2]
```diff
@@ -1225,6 +1239,125 @@ async fn mempool_update_pruned_account() {
...
+    // Send txns to mempool
+    send_txn_to_mempool(&mempool, mock_network, mock_id, txns).await;
+
+    assert_eq!(
+        mempool.num_transactions(),
+        1,
+        "Number of txns in the mempools is not what is expected"
+    );
+
+    //We need a block producer to produce blocks
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]:
```suggestion
    // We need a block producer to produce blocks
```

File: mempool/tests/mod.rs [hunk 3]
```diff
@@ -1225,6 +1239,125 @@ async fn mempool_update_pruned_account() {
...
+            &bc,
+            bc.time.now(),
+            0,
+            None,
+            vec![],
+            updated_txns.clone(),
+            vec![0x41],
+        );
+
+        //We should succeed producing a block with the remaining mempool transactions
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]:
```suggestion
        // We should succeed producing a block with the remaining mempool transactions
```

File: mempool/tests/mod.rs [hunk 4]
```diff
@@ -1225,6 +1239,125 @@ async fn mempool_update_pruned_account() {
...
+    // Get txns from mempool
+    let updated_txns = mempool.get_transactions_for_block(10_000);
+
+    assert_eq!(
+        updated_txns.len(),
+        0,
+        "Number of txns is not what is expected"
+    );
+
+    {
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]: This extra scope could be removed since the end of the scope is the end of the function

File: mempool/tests/mod.rs [hunk 5]
```diff
@@ -1225,6 +1239,125 @@ async fn mempool_update_pruned_account() {
...
+    let mock_id = MockId::new(hub.new_address().into());
+    let mock_network = Arc::new(hub.new_network());
+
+    // Send txns to mempool
+    send_txn_to_mempool(&mempool, mock_network, mock_id, txns).await;
+
+    assert_eq!(
+        mempool.num_transactions(),
+        1,
+        "Number of txns in the mempools is not what is expected"
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]:
```suggestion
        "Number of txns in mempool is not what is expected"
```

**Comment by viquezclaudio** [comment]
@jsdanielh changes applied

**Review by jsdanielh — APPROVED** [review]
