### PR TITLE
utils: Fix some TOCTOU issues

### LINKED ISSUE #2416: Nimiq-client cannot write "signing_key.dat"
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/nimiq-network/core/blob/master/README.md) 
- [x] I have searched [existing issues](https://github.com/nimiq-network/core/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 0.21.0
- Browser version(s): N/A
- Devices/Simulators/Machine affected: Validators
- Reproducible in the testnet? (Yes/No): Yes
- Related issues: None that I can find

## Bug report

While setting up a new validator on a fresh Ubuntu VPS, I ran cargo run and it exits due to 'IO Error: No such file or directory'

#### Expected behavior

"signing_key.day" should be written to ~/core-rs-albatross   (I assume, I cannot find the path details anywhere)

#### Actual behavior

See bug report

#### Steps to reproduce

See bug report

#### Crash log? Screenshots? Videos? Sample project?

2024-05-01T10:06:08.750756035Z DEBUG file_store           | Reading from: /home/ubuntu/.nimiq/peer_key.dat
2024-05-01T10:06:08.750835398Z INFO  client               | Identity public key: PublicKey { publickey: Ed25519(PublicKey(compressed): 1bf33e471dbf3751ee156eb54b30edcc5d371012cd3bc5e1ca192d8ef1236a96) }
2024-05-01T10:06:08.750876417Z INFO  client               | PeerId: 12D3KooWBhUJUy1H44Qs2jBxwdVcVbimSZEHWhzTdYsaUenjyBgR
2024-05-01T10:06:08.750899212Z INFO  client               | Client configured as a full node
2024-05-01T10:06:08.750998003Z DEBUG client               | Listen addresses addresses=["/ip4/0.0.0.0/tcp/8443/ws"]
2024-05-01T10:06:08.751019585Z DEBUG client               | Advertised addresses addresses=Some(["/ip4/51.68.188.164/tcp/8444/ws"])
2024-05-01T10:06:08.752167188Z INFO  libp2p_swarm         | local_peer_id=12D3KooWBhUJUy1H44Qs2jBxwdVcVbimSZEHWhzTdYsaUenjyBgR
2024-05-01T10:06:08.752260830Z INFO  config               | Opening database: testalbatross-full-consensus
2024-05-01T10:06:08.753631615Z INFO  database             | MDBX memory map size cur_mapsize=1099511627776
2024-05-01T10:06:08.769758098Z INFO  zkp_component        | No zk proof found on the db
2024-05-01T10:06:08.769955289Z TRACE sync_queue           | Creating SyncQueue for nimiq_consensus::sync::live::block_queue::block_request_component::MissingBlockResponse with 0 ids and 0 peers
2024-05-01T10:06:08.769988013Z TRACE sync_queue           | Creating SyncQueue for (nimiq_consensus::sync::live::state_queue::ResponseChunk, nimiq_consensus::sync::live::state_queue::RequestChunk, libp2p_identity::peer_id::PeerId) with 0 ids and 0 peers
2024-05-01T10:06:08.770019944Z TRACE sync_queue           | Creating SyncQueue for (nimiq_consensus::messages::RequestHistoryChunk, core::result::Result<nimiq_consensus::messages::HistoryChunk, nimiq_consensus::messages::HistoryChunkError>, libp2p_identity::peer_id::PeerId) with 0 ids and 0 peers
2024-05-01T10:06:08.770213990Z DEBUG file_store           | Writing to file path="signing_key.dat"
2024-05-01T10:06:08.770594458Z ERROR logging              | File store error: IO error: No such file or directory (os error 2)
2024-05-01T10:06:08.770613305Z ERROR logging              |   caused by
2024-05-01T10:06:08.770621199Z ERROR logging              |     IO error: No such file or directory (os error 2)
2024-05-01T10:06:08.770643653Z ERROR logging              |     No such file or directory (os error 2)

### PR DESCRIPTION
**Pull request by hrxi**
https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use

Generally, it's better to try and open a file and check the error to see if it did not exist, rather than trying to figure out the existence of a file using different means.

Do the same for creating parent directories. First, try creating a file. Only if that fails due to the missing parent directory, use `std::fs::create_dir_all` instead of `std::fs::create_dir` to create the parent directory. This function does not fail if the directory already exists. Then, try creating the file again.

### CODE REVIEW

**Review by viquezclaudio — APPROVED** [review]
LGTM

File: utils/src/file_store.rs [hunk 1]
```diff
@@ -19,48 +19,57 @@ impl FileStore {
...
     {
-        if self.path.exists() {
-            self.load()
-        } else {
-            let x = f();
-            self.store(&x)?;
-            Ok(x)
+        match self.load() {
+            Err(Error::Io(err)) if err.kind() == io::ErrorKind::NotFound => {
+                log::debug!(path = ?self.path.display(), "File did not exist, falling back to default");
```
Comment (jsdanielh) [inline utils/src/file_store.rs]:
```suggestion
                log::debug!(path = ?self.path.display(), "File does not exist, falling back to default");
```

Comment (hrxi) [reply utils/src/file_store.rs]: Done.

**Review by Eligioo — APPROVED** [review]

**Review by jsdanielh — APPROVED** [review]
