### PR TITLE
Request macroblock proposal predecessor if unknown

### LINKED ISSUE #321: Rebranching during macro block production (missing test scenario)
At Macro block production we need to make sure that micro blocks in that batch can still be rebranched. If a Validator receives a block on a better chain for which it does not know the predecessor it needs to request the missing blocks and rebranch to that better chain accordingly, entering either micro or macro block production as necessary.

A test scenario is needed for this case, and here's a brief summary of what it could look like.

- Have a network progress to the last micro block of a batch.
- Disconnect the node producer for the last micro block and let him produce it (Node A). This node should have few enough slots such that the others can progress without it, but not by much.
 - This producer will now enter macro block production
- the remaining nodes will view change
- the new block producer produces the block.
- disconnect enough other nodes such that macro block production needs node A to progress.
- reconnect Node A.

The expected behaviour would be that Node A sees a proposal for a chain predecessor it does not know and it should thus request it. In turn that should trigger a rebranch and Node A should enter macro block production on the (better) chain that the other nodes are on, progressing the Network.

### LINKED ISSUE #429: Request the parent block of a proposal if missing
Since 3b52b01bc7f2f2a781526aabaad492bb09b36648, instead of panicking when we don't know the parent of a proposal, we return an error.

This should be improved so that we actually request the missing parent from the network, instead of erroring out and dropping the proposal.

### LINKED ISSUE #1463: Panic in tendermint: "'Preceding block must be a micro block and it must be known"
```
thread 'tokio-runtime-worker' panicked at 'Preceding block must be a micro block and it must be known.': /home/runner/work/core-rs-albatross/core-rs-albatross/validator/src/tendermint.rs:212
   0: <backtrace::capture::Backtrace as core::default::Default>::default
   1: log_panics::Config::install_panic_hook::{{closure}}
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
      std::panicking::rust_panic_with_hook
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:577:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14

```
[validator3.log](https://github.com/nimiq/core-rs-albatross/files/11012258/validator3.log)

Observed in CI run:
https://github.com/nimiq/core-rs-albatross/actions/runs/4462061565/jobs/7836338199

Logs attached

### PR DESCRIPTION
**Pull request by nibhar**
Adds The functionality to resolve a predecessor of a macro block proposal to the validators `ProposalBuffer`. 
This is necessary as a node could potentially not witness a micro block which is superseded by a skip block. Some nodes may have already voted on a proposal on the inferior chain however and in rare circumstances may even have locked themselves on that proposal. Any validator must thus be able to retrieve such inferior chain blocks to verify a macro block proposal.

The resolve missing block request thus had to be adjusted to include a direction, as inferior chain blocks cannot be found by walking the chain forward from a locator. 

Also includes a very minor change I had previously used in this, which is not strictly necessary anymore but I consider it potentially useful enough to include it while it also does not change anything ( f4c5bdac3fa6a8182fd8bb474563829c48baf124 ).

Resolves #1463, Resolves #429, tentatively resolves #321

### CODE REVIEW

File: consensus/src/sync/live/state_queue/live_sync.rs [hunk 1]
```diff
@@ -259,4 +259,8 @@ impl<N: Network> LiveSyncQueue<N> for StateQueue<N> {
     fn state_complete(&self) -> bool {
         self.start_key.is_complete()
     }
+
+    fn resolve_block(&mut self, request: crate::consensus::ResolveBlockRequest<N>) {
```
Comment (jsdanielh) [inline consensus/src/sync/live/state_queue/live_sync.rs]: I'd suggest to add the respective `use`
```suggestion
    fn resolve_block(&mut self, request: ResolveBlockRequest<N>) {
```

File: consensus/src/sync/syncer.rs [hunk 2]
```diff
@@ -163,6 +167,10 @@ impl<N: Network, M: MacroSync<N::PeerId>, L: LiveSync<N>> Syncer<N, M, L> {
     pub fn state_complete(&self) -> bool {
         self.live_sync.state_complete()
     }
+
+    pub fn resolve_block(&mut self, request: ResolveBlockRequest<N>) {
```
Comment (jsdanielh) [inline consensus/src/sync/syncer.rs:172]: Could you add some `rustdoc`?

File: consensus/src/messages/mod.rs [hunk 3]
```diff
@@ -307,7 +309,20 @@ pub struct RequestMissingBlocks {
...
+    ///
+    /// The locator ordering must be from newest to oldest block.
     pub locators: Vec<Blake2bHash>,
+
+    /// The direction the responder should take to search.
+    ///  - Direction::Forward searches from the best locator to the target on the main chain.
+    ///
+    ///     That also implies that any block request using forward direction can only return main chain blocks.
+    ///
+    ///  - Direction::Backward searches from he target hash backwards until a locator (or macro block) is reached.
```
Comment (jsdanielh) [inline consensus/src/messages/mod.rs]:
```suggestion
    ///  - Direction::Backward searches from the target hash backwards until a locator (or macro block) is reached.
```

File: consensus/src/messages/mod.rs [hunk 4]
```diff
@@ -307,7 +309,20 @@ pub struct RequestMissingBlocks {
     pub include_micro_bodies: bool,
     /// Set of hashes of blocks known to the requester, possible starts of the
     /// answer chain.
+    ///
+    /// The locator ordering must be from newest to oldest block.
```
Comment (jsdanielh) [inline consensus/src/messages/mod.rs]: What happens if this assumption doesn't hold?

File: consensus/src/messages/handlers.rs [hunk 5]
```diff
@@ -196,6 +196,102 @@ impl<N: Network> Handle<N, BlockchainProxy> for RequestBlock {
...
+impl RequestMissingBlocks {
+    fn handle_backward<N: Network>(
+        &self,
+        _request_id: N::PeerId,
+        blockchain: &BlockchainProxy,
+    ) -> Result<ResponseBlocks, ResponseBlocksError> {
+        let blockchain = blockchain.read();
+
+        // TODO We might want to do a sanity check on the locator hashes and reject the request if
+        //  they they don't match up with the given target hash.
```
Comment (jsdanielh) [inline consensus/src/messages/handlers.rs]:
```suggestion
        // they they don't match up with the given target hash.
```

File: consensus/src/messages/handlers.rs [hunk 6]
```diff
@@ -196,6 +196,102 @@ impl<N: Network> Handle<N, BlockchainProxy> for RequestBlock {
...
+        }
+    }
+}
+impl RequestMissingBlocks {
+    fn handle_backward<N: Network>(
+        &self,
+        _request_id: N::PeerId,
+        blockchain: &BlockchainProxy,
+    ) -> Result<ResponseBlocks, ResponseBlocksError> {
+        let blockchain = blockchain.read();
```
Comment (jsdanielh) [inline consensus/src/messages/handlers.rs]: We could move this a little further down before the start of the loop

File: consensus/src/sync/live/block_queue/live_sync.rs [hunk 7]
```diff
@@ -134,9 +134,11 @@ impl<N: Network> LiveSyncQueue<N> for BlockQueue<N> {
                 self.remove_invalid_blocks(&mut invalid_blocks);
 
                 if result.is_ok() && !adopted_blocks.is_empty() {
-                    let hash = adopted_blocks.pop().expect("adopted_blocks not empty");
                     return Some(LiveSyncEvent::PushEvent(
-                        LiveSyncPushEvent::ReceivedMissingBlocks(hash, adopted_blocks.len() + 1),
+                        // Verify: Formerly this use to be
+                        // LiveSyncPushEvent::ReceivedMissingBlocks(hash, adopted_blocks.len() + 1),
+                        // What does the + 1 do here?
```
Comment (hrxi) [inline consensus/src/sync/live/block_queue/live_sync.rs]: The `+ 1` probably accounted for the block that was removed via the `pop()` above?

File: consensus/src/sync/live/block_queue/block_request_component.rs [hunk 8]
```diff
@@ -29,11 +30,20 @@ pub enum BlockRequestComponentEvent {
 
 #[derive(Debug, Clone)]
 pub struct MissingBlockRequest {
+    /// The block number of the requested block.
     pub target_block_number: u32,
+    /// The hash the last block which is requested with this request.
     pub target_block_hash: Blake2bHash,
+    /// The validators of the epoch the target block is from.
     pub epoch_validators: Validators,
```
Comment (hrxi) [inline consensus/src/sync/live/block_queue/block_request_component.rs:38]: The field seems to be unused and should probably be removed.

File: consensus/src/consensus/mod.rs [hunk 9]
```diff
@@ -75,28 +75,48 @@ pub enum RemoteEvent {
...
+            }
+            ResolveBlockError::ReceiveError(e) => {
+                write!(f, "ResolveBlockError::ReceiveError({:?})", e)
+            }
+            ResolveBlockError::SendError(e) => {
+                write!(f, "ResolveBlockError::SendError({:?})", e)
+            }
+        }
+    }
+}
```
Comment (hrxi) [inline consensus/src/consensus/mod.rs:100]: There's theoretically [`Formatter::debug_tuple`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html#method.debug_tuple) which does this for you.

File: validator/src/aggregation/tendermint/proposal.rs [hunk 10]
```diff
@@ -92,6 +94,44 @@ impl SignedProposal {
...
+        &self,
+        predecessor: MicroBlock,
+        blockchain: &Blockchain,
+    ) -> bool {
+        // Make sure the proposal references the predecessor as its parent hash
+        if predecessor.hash() != self.proposal.parent_hash {
+            return false;
+        }
+
+        // Make sure the height of he predecessor fits
```
Comment (hrxi) [inline validator/src/aggregation/tendermint/proposal.rs]: the predecessor

File: validator/src/aggregation/tendermint/proposal.rs [hunk 11]
```diff
@@ -92,6 +94,44 @@ impl SignedProposal {
 
         h.finish()
     }
+
+    /// To a given Message and predecessor as well as blockchain, this functions returns true iff
```
Comment (jsdanielh) [inline validator/src/aggregation/tendermint/proposal.rs]:
```suggestion
    /// To a given Message and predecessor as well as blockchain, these functions returns true iff
```

File: validator/src/proposal_buffer.rs [hunk 12]
```diff
@@ -46,54 +65,68 @@ pub(crate) struct ProposalBuffer<TValidatorNetwork: ValidatorNetwork + 'static>
...
+        BoxFuture<
+            'static,
+            Result<
+                (SignedProposal, PubsubId<TValidatorNetwork>),
+                ResolveBlockError<TValidatorNetwork>,
+            >,
+        >,
+    >,
+
+    /// A collection fo peers who currently have a resolve block future pending. Meant to maintain that any
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs]:
```suggestion
    /// A collection for peers who currently have a resolve block future pending. Meant to maintain that any
```

File: validator/src/proposal_buffer.rs [hunk 13]
```diff
@@ -113,6 +146,178 @@ where
...
+    pub fn poll_proposal(
+        &mut self,
+        blockchain_arc: Arc<RwLock<Blockchain>>,
+    ) -> Option<(SignedProposal, PubsubId<TValidatorNetwork>)> {
+        while let Some((_peer, (signed_proposal, pubsub_id))) = self.buffer.pop_front() {
+            // Get a read lock of the blockchain.
+            let blockchain = blockchain_arc.read();
+
+            if blockchain.block_number() >= signed_proposal.proposal.block_number {
+                // Proposal is outdated, drop it and indicate it to not be propagated.
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs]:
```suggestion
                // Proposal is outdated, drop it and indicate the network to not propagate it.
```

File: validator/src/proposal_buffer.rs [hunk 14]
```diff
@@ -113,6 +146,178 @@ where
...
+            )
+            .map(move |result| {
+                match result {
+                    Err(error) => Err(ResolveBlockError::<TValidatorNetwork>::Unresolved(
+                        error, pubsub_id,
+                    )),
+                    Ok(predecessor) => {
+                        // make sure the block is the one that was missing.
+
+                        // Predecessor must be a micro block.
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs]:
```suggestion
                        // make sure the block is the one that was missing.
                        // Predecessor must be a micro block.
```

File: validator/src/proposal_buffer.rs [hunk 15]
```diff
@@ -421,3 +521,429 @@ where
...
+        let nw2 = Arc::new(hub.new_network_with_address(1));
+
+        // Create 2 Temporary block producers.
+        let producer1 = TemporaryBlockProducer::new();
+        let producer2 = TemporaryBlockProducer::new();
+
+        // For Both producers and networks create one consensus each and force establish the consensus on them.
+        let consensus1 = consensus(Arc::clone(&producer1.blockchain), Arc::clone(&nw1)).await;
+
+        let consensus2 = consensus(Arc::clone(&producer2.blockchain), Arc::clone(&nw2)).await;
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs]:
```suggestion
        let consensus1 = consensus(Arc::clone(&producer1.blockchain), Arc::clone(&nw1)).await;
        let consensus2 = consensus(Arc::clone(&producer2.blockchain), Arc::clone(&nw2)).await;
```

File: validator/src/proposal_buffer.rs [hunk 16]
```diff
@@ -421,3 +521,429 @@ where
...
+            .unwrap();
+
+        let _signed_proposal = tokio::time::timeout_at(deadline, proposal_receiver.next())
+            .await
+            .expect("proposal buffer should have produced the proposal before the timeout")
+            .expect("proposal buffer should have produced the proposal");
+    }
+
+    /// Has a validator creating a batch worth of blocks and a proposal for the macro block.
+    /// Also has a secondary proposal buffer witness all but the last micro block. Lets the buffer
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs]:
```suggestion
    /// Also has a secondary proposal buffer that witness all but the last micro block. Lets the buffer
```

File: validator/src/proposal_buffer.rs [hunk 17]
```diff
@@ -421,3 +521,429 @@ where
...
+
+        // Create a proposal from node 1 for node 2.
+        let proposal =
+            create_proposal_msg(nw1, nw2, signing_key, macro_block.header().unwrap_macro()).await;
+
+        // Push the proposal into the ProposalBuffer
+        proposal_sender.send(proposal);
+
+        // Poll the ProposalBuffer until it produces a proposal. This should resolve the so far unknown predecessor and resolve.
+        // do this with a timeout as it should really only take a single round trip.
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs]:
```suggestion
        // Do this with a timeout as it should really only take a single round trip.
```

File: validator/src/proposal_buffer.rs [hunk 18]
```diff
@@ -421,3 +521,429 @@ where
...
+            .expect("Must be able to get the predecessor after resolving it.");
+
+        // Finally push the macro block the proposal is for. It should not be an Orphan
+        producer2
+            .push(macro_block)
+            .expect("pushing the macro block must work");
+    }
+
+    /// Has a validator creating a batch worth of blocks and a proposal for the macro block.
+    /// Also has a secondary proposal buffer witness all but the last two micro blocks. Lets the buffer
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs]:
```suggestion
    /// Also has a secondary proposal buffer that witness all but the last two micro blocks. Lets the buffer
```

File: validator/src/proposal_buffer.rs [hunk 19]
```diff
@@ -421,3 +521,429 @@ where
...
+    /// see the proposal and make it resolve the blocks.
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs]:
```suggestion
    /// see the proposal and makes it resolve the blocks.
```

File: validator/src/proposal_buffer.rs [hunk 20]
```diff
@@ -421,3 +521,429 @@ where
...
+
+        let _signed_proposal = tokio::time::timeout_at(deadline, proposal_receiver.next())
+            .await
+            .expect("proposal buffer should have produced the proposal before the timeout")
+            .expect("proposal buffer should have produced the proposal");
+    }
+
+    /// Has a validator creating a batch worth of blocks and a proposal for the macro block.
+    /// Also has a secondary proposal buffer witness all but the last micro block. Lets the buffer
+    /// see the proposal and make it resolve the block.
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs]:
```suggestion
    /// see the proposal and makes it resolve the block.
```

File: validator/src/proposal_buffer.rs [hunk 21]
```diff
@@ -421,3 +521,429 @@ where
...
+
+        // Create a proposal from node 1 for node 2.
+        let proposal =
+            create_proposal_msg(nw1, nw2, signing_key, macro_block.header().unwrap_macro()).await;
+
+        // Push the proposal into the ProposalBuffer
+        proposal_sender.send(proposal);
+
+        // Poll the ProposalBuffer until it produces a proposal. This should resolve the so far unknown predecessor and resolve.
+        // do this with a timeout as it should really only take a single round trip.
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs]:
```suggestion
        // Do this with a timeout as it should really only take a single round trip.
```

File: validator/src/proposal_buffer.rs [hunk 22]
```diff
@@ -421,3 +521,429 @@ where
...
+            .expect("Must be able to get the predecessor after resolving it.");
+
+        // Finally push the macro block the proposal is for. It should not be an Orphan
+        producer2
+            .push(macro_block)
+            .expect("pushing the macro block must work");
+    }
+
+    /// Has a validator creating a batch worth of blocks and a proposal for the macro block.
+    /// Also has a secondary proposal buffer witness all but the last micro block but let it also see a skip block instead.
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs:883]:
```suggestion
    /// Also has a secondary proposal buffer that witness all but the last micro block but let it also see a skip block instead.
```

File: validator/src/proposal_buffer.rs [hunk 23]
```diff
@@ -421,3 +521,429 @@ where
...
+    /// Lets the buffer see the proposal and make it resolve the block.
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs]:
```suggestion
    /// Lets the buffer see the proposal and makes it resolve the block.
```

File: validator/src/proposal_buffer.rs [hunk 24]
```diff
@@ -421,3 +521,429 @@ where
...
+
+        // Create a proposal from node 1 for node 2.
+        let proposal =
+            create_proposal_msg(nw1, nw2, signing_key, macro_block.header().unwrap_macro()).await;
+
+        // Push the proposal into the ProposalBuffer
+        proposal_sender.send(proposal);
+
+        // Poll the ProposalBuffer until it produces a proposal. This should resolve the so far unknown predecessor and resolve.
+        // do this with a timeout as it should really only take a single round trip.
```
Comment (jsdanielh) [inline validator/src/proposal_buffer.rs]:
```suggestion
        // Do this with a timeout as it should really only take a single round trip.
```

File: consensus/src/sync/live/block_queue/live_sync.rs [hunk 25]
```diff
@@ -134,9 +134,11 @@ impl<N: Network> LiveSyncQueue<N> for BlockQueue<N> {
                 self.remove_invalid_blocks(&mut invalid_blocks);
 
                 if result.is_ok() && !adopted_blocks.is_empty() {
-                    let hash = adopted_blocks.pop().expect("adopted_blocks not empty");
                     return Some(LiveSyncEvent::PushEvent(
-                        LiveSyncPushEvent::ReceivedMissingBlocks(hash, adopted_blocks.len() + 1),
+                        // Verify: Formerly this use to be
```
Comment (jsdanielh) [inline consensus/src/sync/live/block_queue/live_sync.rs]:
```suggestion
                        // Verify: Formerly this used to be
```

File: consensus/src/sync/live/block_queue/mod.rs [hunk 26]
```diff
@@ -545,6 +577,52 @@ impl<N: Network> BlockQueue<N> {
...
+    fn prune_pending_requests(&mut self) {
+        self.pending_requests.retain(|&block_number, senders| {
+            // Blocks which are after the current macro height are retained as they retain relevance.
+            if block_number > self.current_macro_height {
+                return true;
+            }
+
+            // Resolve all of the pending requests which were removed as outdated.
+            // Obviously the requests themselves do not terminate, but they resolve on the caller side. The request
+            // yielding a result becomes inconsequential, as the block it would yields can no longer be pushed.
```
Comment (jsdanielh) [inline consensus/src/sync/live/block_queue/mod.rs]:
```suggestion
            // yielding a result becomes inconsequential, as the block it would yield can no longer be pushed.
```

File: consensus/src/sync/live/block_queue/mod.rs [hunk 27]
```diff
@@ -561,6 +639,70 @@ impl<N: Network> BlockQueue<N> {
...
+                // pubsub_id thus giving more options to actually resolve the block in terms of peers ot ask.
+            }
+            HashMapEntry::Vacant(entry) => {
+                entry.insert(response_sender);
+            }
+        };
+
+        // Check if the block in question is already buffered or pending a push.
+
+        if self
```
Comment (jsdanielh) [inline consensus/src/sync/live/block_queue/mod.rs]:
```suggestion
        // Check if the block in question is already buffered or pending a push.
        if self
```

File: consensus/src/sync/live/block_queue/live_sync.rs (hunk 7 above)
Comment (nibhar) [reply consensus/src/sync/live/block_queue/live_sync.rs]: Removed the comment. Thanks for pointing it out!

File: consensus/src/sync/live/block_queue/block_request_component.rs (hunk 8 above)
Comment (nibhar) [reply consensus/src/sync/live/block_queue/block_request_component.rs:38]: https://github.com/nimiq/core-rs-albatross/blob/albatross/consensus/src/sync/live/block_queue/block_request_component.rs#L185 I do not think it is unused.

File: consensus/src/consensus/mod.rs (hunk 9 above)
Comment (nibhar) [reply consensus/src/consensus/mod.rs:100]: I changed it though it does not really save much here. Maybe I also misunderstand how `debug_tuple` is supposed to be used for enums.

File: consensus/src/messages/mod.rs (hunk 4 above)
Comment (nibhar) [reply consensus/src/messages/mod.rs]: Added a clarifying comment.

File: validator/src/aggregation/tendermint/proposal.rs (hunk 11 above)
Comment (nibhar) [reply validator/src/aggregation/tendermint/proposal.rs]: Changed it to `this function` instead.

File: validator/src/proposal_buffer.rs (hunk 12 above)
Comment (nibhar) [reply validator/src/proposal_buffer.rs]: Changed it to `collection of peers` instead.

File: consensus/src/sync/live/block_queue/live_sync.rs (hunk 25 above)
Comment (nibhar) [reply consensus/src/sync/live/block_queue/live_sync.rs]: Removed the comment after @hrxi clarification

**Review by jsdanielh — APPROVED** [review]
LGTM

**Comment by jsdanielh** [comment]
Rebasing and signing commits

File: consensus/src/sync/live/block_queue/block_request_component.rs (hunk 8 above)
Comment (hrxi) [reply consensus/src/sync/live/block_queue/block_request_component.rs:38]: The field seems to be used – by the requester? That seems super weird. Why would we send it over the network for this?

https://github.com/nimiq/core-rs-albatross/blob/85ddc9083c43fd175a2273f7f52855adacd50b18/consensus/src/sync/live/block_queue/block_request_component.rs#L196

Comment (hrxi) [reply consensus/src/sync/live/block_queue/block_request_component.rs:38]: Sorry, I was confused. It's not sent over the network.
