### PR TITLE
Fix multiple OpenRPC schema issues

### LINKED ISSUE #3499: OpenRPC schema: subscribeForLogsByAddressesAndTypes addresses param should be array
The OpenRPC schema incorrectly defines the `addresses` parameter as `string` instead of `array`:

```json
{
  "name": "addresses",
  "schema": {
    "type": "string"  // ← Should be array
  }
}
```

The Rust implementation correctly expects `Vec<Address>`:
```rust
async fn subscribe_for_logs_by_addresses_and_types(
    addresses: Vec<Address>,
    log_types: Vec<LogType>,
)
```

The method description also states "list of addresses", confirming it should be an array.

**Fix:** Change schema to:
```json
{
  "name": "addresses",
  "schema": {
    "type": "array",
    "items": { "type": "string" }
  }
}
```

### LINKED ISSUE #3500: OpenRPC schema: updateValidator params should be nullable
The OpenRPC schema incorrectly defines update validator parameters as required strings, but the Rust implementation uses `Option` types:

**Rust implementation:**
```rust
new_signing_secret_key: Option<String>,
new_voting_secret_key: Option<String>,
new_reward_address: Option<Address>,
new_signal_data: Option<String>,
```

**Schema should allow null** for these parameters to indicate "no change".

Affected methods:
- `createUpdateValidatorTransaction`
- `sendUpdateValidatorTransaction`

### LINKED ISSUE #3501: OpenRPC schema: MempoolInfo keys should have underscores
The OpenRPC schema incorrectly defines MempoolInfo keys as numeric strings ("0", "1", etc.), but the Rust implementation uses underscored names:

**Rust implementation:**
```rust
pub struct MempoolInfo {
    pub _0: Option<u32>,
    pub _1: Option<u32>,
    pub _2: Option<u32>,
    // etc.
}
```

**Schema should use** "_0", "_1", etc. instead of "0", "1".

### LINKED ISSUE #3503: OpenRPC schema: PenalizedSlots.disabled should be array not object
The OpenRPC schema incorrectly defines `disabled` as `object`, but BitSet serializes as an array for JSON:

**Rust implementation:**
```rust
pub struct PenalizedSlots {
    pub disabled: BitSet,  // Serializes as number[]
}
```

**Schema should define** `disabled` as `array` of numbers, not `object`.

### LINKED ISSUE #3504: OpenRPC schema: validityStartHeight should accept string or number
The OpenRPC schema defines `validityStartHeight` parameter as `type: number` for all transaction creation methods. However, the Rust server's `ValidityStartHeight` deserializer accepts both:
- Numbers (interpreted as Absolute)
- Strings (parsed as "+N" for Relative, "N" for Absolute)

This allows clients to use the "+" prefix syntax for relative validity start heights, which is the intended API design.

**Issue:** The schema should document that this parameter accepts either:
- `string` (preferred, supports "+N" relative syntax)
- `number` (absolute only)

**Affected methods:** All transaction creation/sending methods (createBasicTransaction, sendBasicTransaction, createNewStakerTransaction, etc.)

**Reference:** 
- Deserializer: rpc-interface/src/types.rs `impl<'de> Deserialize<'de> for ValidityStartHeight`
- Display impl shows the intended format: `+N` for relative, `N` for absolute

### LINKED ISSUE #3505: OpenRPC schema: All RPC results should be documented as RPCData envelope
The OpenRPC schema defines each method's result as the direct value type (e.g., `number` for getBlockNumber). However, the Rust server wraps ALL RPC method results in the `RPCData<T, S>` envelope structure:

```rust
pub struct RPCData<T, S> {
    pub data: T,
    pub metadata: S,
}
```

**Actual server response format:**
```json
{
  "result": {
    "data": <actual value>,
    "metadata": <metadata or null>
  }
}
```

**What the schema currently says:**
```json
{
  "result": <actual value>
}
```

**Issue:** The OpenRPC schema should document that all method results follow the `{ data, metadata }` envelope pattern, not return the raw value directly.

**Affected methods:** ALL RPC methods

**Reference:** 
- Type definition: rpc-interface/src/types.rs `pub struct RPCData<T, S>`
- Result type: rpc-interface/src/types.rs `pub type RPCResult<T, S, E> = Result<RPCData<T, S>, E>`

### PR DESCRIPTION
**Pull request by onmax**
## What's in this pull request?

I have an automation that continuously diff-checks the generated JSON-RPC schema against my TypeScript client (`onmax/albatross-rpc-client-ts`). The pipeline runs strong validations, replays real request/response samples, and finishes with an LLM-based review (`scripts/validate-schema.ts`, lines 237-264) to ensure the library stays in sync with the protocol surface. I execute this end-to-end process roughly once per month.

Yesterday I closed every issue that the AI surfaced inside the TS codebase (see [closed issues](https://github.com/onmax/albatross-rpc-client-ts/issues?q=is%3Aissue+state%3Aclosed+sort%3Aupdated-desc)). What remained were discrepancies caused by the OpenRPC generator itself. This PR fixes those schema gaps so that the dev-center JSON reflects the real Rust behaviour.

For each schema fix below you will find the impacted RPC methods with **two links**:
1. The current "official" documentation on developer.nimiq.com.
2. The preview that is deployed from [nimiq/developer-center#158](https://github.com/nimiq/developer-center/pull/158) so you can diff them quickly.

## Important
- Every line in this PR was produced with AI assistance. The implementation might not be the most optimal solution, but it is fully validated by the automated pipeline described above.

## Summary
Fixes #3499, #3500, #3501, #3503, #3504, #3505 — multiple OpenRPC schema corrections so the spec matches the Rust implementation.

### #3499: `subscribeForLogsByAddressesAndTypes` addresses becomes an array (branch `fix/openrpc-array-param-schema`)
<details>
<summary>📋 Details</summary>

| Method | Official | Preview |
| --- | --- | --- |
| `subscribeForLogsByAddressesAndTypes` | [official](https://developer.nimiq.com/rpc/methods/subscribeForLogsByAddressesAndTypes) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/subscribeForLogsByAddressesAndTypes) |

</details>

### #3500: Optional update-validator parameters (commit `565d67e`)
<details>
<summary>📋 Details</summary>

| Method | Official | Preview |
| --- | --- | --- |
| `createUpdateValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/createUpdateValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createUpdateValidatorTransaction) |
| `sendUpdateValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendUpdateValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendUpdateValidatorTransaction) |

</details>

### #3501: Preserve underscore-prefixed MempoolInfo fields (commit `8fbfd4b`)
<details>
<summary>📋 Details</summary>

| Method | Official | Preview |
| --- | --- | --- |
| `mempool` | [official](https://developer.nimiq.com/rpc/methods/mempool) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/mempool) |

</details>

### #3503: `PenalizedSlots.disabled` as an array of numbers (commit `a4ab5c8`)
<details>
<summary>📋 Details</summary>

| Method | Official | Preview |
| --- | --- | --- |
| `getCurrentPenalizedSlots` | [official](https://developer.nimiq.com/rpc/methods/getCurrentPenalizedSlots) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/getCurrentPenalizedSlots) |
| `getPreviousPenalizedSlots` | [official](https://developer.nimiq.com/rpc/methods/getPreviousPenalizedSlots) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/getPreviousPenalizedSlots) |

</details>

### #3504: `validityStartHeight` accepts numbers **or** strings everywhere (commit `757640d`)
<details>
<summary>📋 Details</summary>

| Method | Official | Preview |
| --- | --- | --- |
| `createBasicTransaction` | [official](https://developer.nimiq.com/rpc/methods/createBasicTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createBasicTransaction) |
| `createBasicTransactionWithData` | [official](https://developer.nimiq.com/rpc/methods/createBasicTransactionWithData) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createBasicTransactionWithData) |
| `createDeactivateValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/createDeactivateValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createDeactivateValidatorTransaction) |
| `createDeleteValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/createDeleteValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createDeleteValidatorTransaction) |
| `createNewHtlcTransaction` | [official](https://developer.nimiq.com/rpc/methods/createNewHtlcTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createNewHtlcTransaction) |
| `createNewStakerTransaction` | [official](https://developer.nimiq.com/rpc/methods/createNewStakerTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createNewStakerTransaction) |
| `createNewValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/createNewValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createNewValidatorTransaction) |
| `createNewVestingTransaction` | [official](https://developer.nimiq.com/rpc/methods/createNewVestingTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createNewVestingTransaction) |
| `createReactivateValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/createReactivateValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createReactivateValidatorTransaction) |
| `createRedeemEarlyHtlcTransaction` | [official](https://developer.nimiq.com/rpc/methods/createRedeemEarlyHtlcTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createRedeemEarlyHtlcTransaction) |
| `createRedeemRegularHtlcTransaction` | [official](https://developer.nimiq.com/rpc/methods/createRedeemRegularHtlcTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createRedeemRegularHtlcTransaction) |
| `createRedeemTimeoutHtlcTransaction` | [official](https://developer.nimiq.com/rpc/methods/createRedeemTimeoutHtlcTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createRedeemTimeoutHtlcTransaction) |
| `createRedeemVestingTransaction` | [official](https://developer.nimiq.com/rpc/methods/createRedeemVestingTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createRedeemVestingTransaction) |
| `createRemoveStakeTransaction` | [official](https://developer.nimiq.com/rpc/methods/createRemoveStakeTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createRemoveStakeTransaction) |
| `createRetireStakeTransaction` | [official](https://developer.nimiq.com/rpc/methods/createRetireStakeTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createRetireStakeTransaction) |
| `createRetireValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/createRetireValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createRetireValidatorTransaction) |
| `createSetActiveStakeTransaction` | [official](https://developer.nimiq.com/rpc/methods/createSetActiveStakeTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createSetActiveStakeTransaction) |
| `createStakeTransaction` | [official](https://developer.nimiq.com/rpc/methods/createStakeTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createStakeTransaction) |
| `createUpdateStakerTransaction` | [official](https://developer.nimiq.com/rpc/methods/createUpdateStakerTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createUpdateStakerTransaction) |
| `createUpdateValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/createUpdateValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/createUpdateValidatorTransaction) |
| `sendBasicTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendBasicTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendBasicTransaction) |
| `sendBasicTransactionWithData` | [official](https://developer.nimiq.com/rpc/methods/sendBasicTransactionWithData) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendBasicTransactionWithData) |
| `sendDeactivateValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendDeactivateValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendDeactivateValidatorTransaction) |
| `sendDeleteValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendDeleteValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendDeleteValidatorTransaction) |
| `sendNewHtlcTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendNewHtlcTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendNewHtlcTransaction) |
| `sendNewStakerTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendNewStakerTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendNewStakerTransaction) |
| `sendNewValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendNewValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendNewValidatorTransaction) |
| `sendNewVestingTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendNewVestingTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendNewVestingTransaction) |
| `sendReactivateValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendReactivateValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendReactivateValidatorTransaction) |
| `sendRedeemEarlyHtlcTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendRedeemEarlyHtlcTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendRedeemEarlyHtlcTransaction) |
| `sendRedeemRegularHtlcTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendRedeemRegularHtlcTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendRedeemRegularHtlcTransaction) |
| `sendRedeemTimeoutHtlcTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendRedeemTimeoutHtlcTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendRedeemTimeoutHtlcTransaction) |
| `sendRedeemVestingTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendRedeemVestingTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendRedeemVestingTransaction) |
| `sendRemoveStakeTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendRemoveStakeTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendRemoveStakeTransaction) |
| `sendRetireStakeTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendRetireStakeTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendRetireStakeTransaction) |
| `sendRetireValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendRetireValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendRetireValidatorTransaction) |
| `sendSetActiveStakeTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendSetActiveStakeTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendSetActiveStakeTransaction) |
| `sendStakeTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendStakeTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendStakeTransaction) |
| `sendUpdateStakerTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendUpdateStakerTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendUpdateStakerTransaction) |
| `sendUpdateValidatorTransaction` | [official](https://developer.nimiq.com/rpc/methods/sendUpdateValidatorTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/sendUpdateValidatorTransaction) |
| `signRedeemEarlyHtlcTransaction` | [official](https://developer.nimiq.com/rpc/methods/signRedeemEarlyHtlcTransaction) | [preview](https://deploy-preview-158--nimiq-developer-center.netlify.app/rpc/methods/signRedeemEarlyHtlcTransaction) |

</details>

### #3505: Document the `RPCData { data, metadata }` envelope for every response (commit `757640d`)
<details>
<summary>📋 Details</summary>

All RPC responses now reference the `{ data, metadata }` schema instead of pretending that the raw value is returned at the top level. This is visible across every method page in the preview as well as inside `.vitepress/rpc/openrpc-document.json` from developer-center PR #158.

</details>

### Bonus fix: Flattened tagged enums and discriminators (commit `d3bd782`)
<details>
<summary>📋 Details</summary>

- `Account` responses now expose the variant discriminator (`type`) and merge the fields for Basic/Vesting/HTLC/Staking directly at the top level, matching `#[serde(flatten)]`.
- `Block` responses do the same for Macro vs Micro blocks, including the per-variant optional arrays and proof fields.
- `ExecutedTransaction` keeps `transaction` flattened so schema-aware clients can see every property.

Preview the diffs for these types in [developer-center#158](https://github.com/nimiq/developer-center/pull/158/files) (`.vitepress/rpc/openrpc-document.json`).

</details>

### Bonus fix: Generic type panic (commit `757640d`)
<details>
<summary>📋 Details</summary>

While adding the RPCData envelope we also hardened the parser so it no longer panics when encountering nested generic arguments that do not have an explicit schema entry (e.g., tuples or `Vec<(Hash, u32)>`).

</details>

## Schema comparison
- Full schema artifact (official vs preview) can be inspected in [nimiq/developer-center#158 (files tab)](https://github.com/nimiq/developer-center/pull/158/files).
- Once CI finishes, Netlify will expose the preview under `https://deploy-preview-158--nimiq-developer-center.netlify.app/` so you can click through the Dev Center UI side-by-side with the production site.

### CODE REVIEW

**Review by jsdanielh — APPROVED** [review]

File: tools/src/rpc-schema/parser.rs [hunk 1]
```diff
@@ -266,11 +384,15 @@ impl ParsedTraitItemFn {
...
     /// Determines whether a Rust trait method parameter is required.
-    fn param_required(_ty: &Type) -> bool {
-        // At the moment, all params are required even if the type is wrapped in an Option.
-        // if ty.to_token_stream().to_string().contains("Option") {
-        //     return false;
-        // }
+    fn param_required(ty: &Type) -> bool {
+        if let Type::Path(type_path) = ty {
+            let is_option = type_path
+                .path
```
Comment (Eligioo) [inline tools/src/rpc-schema/parser.rs]: This unfortunately doesn't hold. RPC params wrapped in an `Option<>` still need to be provided as a default value. 

The following example (even without the `params` field) is not accepted by the RPC server.
```
{
	"jsonrpc": "2.0",
	"method": "createAccount",
	"params": [],
	"id": 1
}
```

File: tools/src/rpc-schema/parser.rs [hunk 2]
```diff
@@ -336,6 +334,62 @@ impl ParsedTraitItemFn {
             .first()
             .expect("Path must have an identity.");
 
+        // Check if this is RPCData - if so, we need to wrap in envelope
+        if ident.ident == "RPCData" {
```
Comment (Eligioo) [inline tools/src/rpc-schema/parser.rs]: Why do we need to handle this case?

File: tools/src/rpc-schema/parser.rs [hunk 3]
```diff
@@ -441,12 +630,14 @@ impl ParsedTraitItemFn {
...
-                    return (segment.to_owned(), segment.ident.clone());
+                if let PathArguments::AngleBracketed(outer_type) = &path_segment.arguments {
+                    if let Some(GenericArgument::Type(Type::Path(inner_type))) =
+                        outer_type.args.first()
+                    {
+                        let segment = inner_type.path.segments.first().unwrap();
+                        return (segment.to_owned(), segment.ident.clone());
+                    }
+                    // For other types (like tuples), return the original path
                 }
```
Comment (Eligioo) [inline tools/src/rpc-schema/parser.rs]: Please fix all the Clippy warnings

**Review by Eligioo — CHANGES_REQUESTED** [review]

File: tools/src/rpc-schema/parser.rs (hunk 2 above)
Comment (onmax) [reply tools/src/rpc-schema/parser.rs]: we dont need it

File: tools/src/rpc-schema/parser.rs (hunk 1 above)
Comment (onmax) [reply tools/src/rpc-schema/parser.rs]: resolved i think?

**Review by Eligioo — APPROVED** [review]

**Comment by onmax** [comment]
dont merge. i need to test something in dev center

**Comment by onmax** [comment]
ok, all good.

you can check out the preview of the new RPC json document here https://deploy-preview-158--developer-center.netlify.app/rpc/methods/

**Comment by onmax** [comment]
@jsdanielh merge whenever you want
