### PR TITLE
Fix production of invalid history chunks

### LINKED ISSUE #2890: Invalid history chunks
In the test net, it has been observed the following log messages:

`Banning peer because the validity history chunk didn't verify peer_id=12D3KooWKd6cY4saxrTradfE5ELkxDFNWTC3Vn79H8ckNQDREA75 chunk=138 verifier_block=3549090 epoch=12`

This is caused by a peer behind who generated a history chunk proof that doesn't verify because the verifier block number is ahead of his current state. This led to an improper banning of the peer.

For this case (server is behind), we should reply that we couldn't produce the proof such that the peer is emitted as outdated and not banned

### PR DESCRIPTION
**Pull request by viquezclaudio**
- Do not produce invalid history chunks if the verifier block number is ahead of our state
- Improve the validity window sync (log & process)

## Pull request checklist

- [ ] All tests pass. The project builds and runs.
- [ ] I have resolved any merge conflicts.
- [ ] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

File: blockchain/src/history/history_store.rs [hunk 1]
```diff
@@ -416,19 +421,19 @@ impl HistoryInterface for HistoryStore {
...
-                        i + 1
+                        Some(i + 1)
                     } else {
-                        0
+                        Some(0)
                     }
                 }
                 // If it doesn't exist, then the HistoryStore is empty at this block height.
-                None => 0,
+                None => None,
```
Comment (sisou) [inline blockchain/src/history/history_store.rs]: If you're just forwarding `None`, you should be able to use `Option::map` instead on `cursor.prev()`.

**Review by ii-cruz — APPROVED** [review]
LGTM
