### PR TITLE
libp2p: Re-implement the request/response decoding

### LINKED ISSUE #744: Requests sometimes fail to be decoded
In [this CI run](https://github.com/nimiq/core-rs-albatross/actions/runs/2057905327) validator 1 presented issues to decode requests in the `FourValidatorsReconnectSpammer` test:
```
2022-03-29T10:33:43.747228Z DEBUG libp2p_swarm         | Connection closed with error Handler(B(Upgrade(Apply(Custom { kind: Other, error: "Fail to decode request" })))): Connected { endpoint: Dialer { address: "/ip4/127.0.0.1/tcp/9103/ws/p2p/12D3KooWCadZ3N9yG5cjTuLhsEpSQi2gxJnur8BmZuThRhzMF4F4", role_override: Dialer }, peer_id: PeerId("12D3KooWCadZ3N9yG5cjTuLhsEpSQi2gxJnur8BmZuThRhzMF4F4") }; Total (peer): 0.    , swarm task{peer_id=PeerId("12D3KooWDmiBBP4e5rBgaFdZd5XZH3q7RHpNgwi4JUXck3hDHQx5")}
2022-03-29T10:33:43.747939Z DEBUG behaviour            | Maintaining peers: connected=4, dialing=0, failed=0, down=1 | addresses: connected=4, dialing=0, failed=0, down=0, swarm task{peer_id=PeerId("12D3KooWDmiBBP4e5rBgaFdZd5XZH3q7RHpNgwi4JUXck3hDHQx5")}
2022-03-29T10:33:43.763798Z INFO  network              | Connection closed with peer 12D3KooWCadZ3N9yG5cjTuLhsEpSQi2gxJnur8BmZuThRhzMF4F4, Dialer { address: "/ip4/127.0.0.1/tcp/9103/ws/p2p/12D3KooWCadZ3N9yG5cjTuLhsEpSQi2gxJnur8BmZuThRhzMF4F4", role_override: Dialer }, connections established: 0, swarm task{peer_id=PeerId("12D3KooWDmiBBP4e5rBgaFdZd5XZH3q7RHpNgwi4JUXck3hDHQx5")}
2022-03-29T10:33:43.764188Z INFO  network              | Connection closed because: Handler(B(Upgrade(Apply(Custom { kind: Other, error: "Fail to decode request" })))), swarm task{peer_id=PeerId("12D3KooWDmiBBP4e5rBgaFdZd5XZH3q7RHpNgwi4JUXck3hDHQx5")}
```
Then it results in peer connections being closed.

### PR DESCRIPTION
**Pull request by jsdanielh**
Re-implement the request/response message decoding without using
the `Decoder` trait from `tokio` and simplifying the logic since
there is no need to handle frames via buffers and no state has to be
tracked across different decoding calls.
This also avoids issues since different `read_requests` or
`read_responses` could be called asynchronously causing race
conditions with the internal state as seen in #744.

This fixes #744.

### CODE REVIEW

File: network-libp2p/src/dispatch/codecs/typed.rs [hunk 1]
```diff
@@ -193,6 +193,55 @@ impl MessageCodec {
 
         Ok(())
     }
+
+    fn decode_serialized_message(
```
Comment (hrxi) [inline network-libp2p/src/dispatch/codecs/typed.rs]: Both this function and `fn verify` can be made static.

File: network-libp2p/src/dispatch/codecs/typed.rs [hunk 2]
```diff
@@ -193,6 +193,55 @@ impl MessageCodec {
...
+
+        // Drop the cursor, so we can mut-borrow the `src` buffer again.
+        drop(c);
+
+        // Preliminary header check (we can't verify the checksum yet)
+        header.preliminary_check()?;
+
+        // Now parse the body.
+        if src.len() >= header.length as usize {
+            // We have read enough bytes to read the full message
```
Comment (hrxi) [inline network-libp2p/src/dispatch/codecs/typed.rs]: This is kinda misleading, it sounds like it could wait for more data.
```suggestion
            // We have at least as much bytes as the header indicated
```

Could this be an equality check instead?

File: network-libp2p/src/dispatch/codecs/typed.rs [hunk 3]
```diff
@@ -193,6 +193,55 @@ impl MessageCodec {
...
+            })?;
+
+            // Skip the header to have only the data
+            data.advance(header_length);
+
+            Ok((MessageType::new(message_type), data))
+        } else {
+            // Header size doesn't match the buffer size
+            log::error!(
+                "Request/response decoding error: Header size doesn't match the buffer size"
```
Comment (hrxi) [inline network-libp2p/src/dispatch/codecs/typed.rs:234]: If the condition above isn't rewritten to an equality, maybe it could be:
```suggestion
                "Request/response decoding error: Header indicates larger size than the body has"
```
Also, the comment above is redundant, it just repeats the log message.

**Review by hrxi — COMMENTED** [review]
Looks good to me aside from the comments I left. Could you comment on the questions I had?

File: network-libp2p/src/dispatch/codecs/typed.rs (hunk 2 above)
Comment (jsdanielh) [reply network-libp2p/src/dispatch/codecs/typed.rs]: > Could this be an equality check instead?

You're right. It should be an equality.

**Comment by hrxi** [comment]
Nice, LGTM. :)
