### PR TITLE
Remove all the unstable features, compile on stable

### LINKED ISSUE #689: Make core-rs-albatross run on Rust stable
This would stop us being hit by broken nightlies, and is generally desirable for a release.

I took a look again, and it does seem feasible. Not sure why I thought otherwise before, maybe I'll find out while trying.

### PR DESCRIPTION
**Pull request by hrxi**
Fixes #689.

### CODE REVIEW

File: consensus/src/sync/block_queue.rs [hunk 1]
```diff
@@ -388,26 +391,31 @@ impl<N: Network> Inner<N> {
...
             // Remove all entries from the block buffer that precede `current_macro_height`.
-            if *entry.key() > self.current_macro_height {
-                break;
+            if block_number > self.current_macro_height {
+                return true;
             }
             // Tell gossipsub to ignore the removed blocks.
-            for (_, (_, pubsub_id)) in entry.remove().into_iter() {
-                self.report_validation_result(pubsub_id, MsgAcceptance::Ignore);
+            for (_, (_, pubsub_id)) in blocks {
```
Comment (jsdanielh) [inline consensus/src/sync/block_queue.rs]: @hrxi Could you address the clippy warning?

**Review by jsdanielh — CHANGES_REQUESTED** [review]

File: consensus/src/sync/block_queue.rs (hunk 1 above)
Comment (hrxi) [reply consensus/src/sync/block_queue.rs]: Done.

**Review by jsdanielh — APPROVED** [review]
