### PR TITLE
Return RPC error if there are invalid params

### LINKED ISSUE #1483: Panic at `RPC-Server:@sendNewValidatorTransaction`
Making any of the following requests will result in a panic in the RPC server:

### 1. Incorrect order (should be ADDRESS SIGNING_KEY VOTING_KEY)

```bash
arpl validator:new "NQ81 4FM0 HX81 CR06 V5ET SMNF 73YF HRL7 6M1L" "9186586c299f7ece42f0b0c9741d684d261422f107601ce054c9bda7c522ad150b742485c9d8d43a86fa65668d1288c32d41e16e0d77221c861e1bc5ba10c17c99c698488b15285fc53d9c3544c0f1d3869c283d88fcb917571fb60fc68101" "b930e8fc121ed19e55820d16db1309921384bef06109d3a892170df3a962bfb3" --url http://localhost:10300
```

### 2. Invalid params
```bash
arpl validator:new "NQ81 4FM0 HX81 CR06 V5ET SMNF 73YF HRL7 6M1L" "NOT VALID" "NOT VALID" --url http://localhost:10300
```

[Docs for arpl@validator:new](https://github.com/sisou/arpl#arpl-validatornew-wallet-signing_secret_key-voting_secret_key)

Even though, the RPC server panics, the execution of the node continue.

## Expected behaviour

Get a nice RPC error response.

### PR DESCRIPTION
**Pull request by onmax**
## What's in this pull request?

Return error on invalid params: `signing_key`, `voting_key` and `signal_data`

## Pull request checklist

- [x] All tests pass. The project builds and runs.
- [X] I have resolved any merge conflicts.
- [x] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

**Review by sisou — APPROVED** [review]

**Review by jsdanielh — APPROVED** [review]

File: rpc-server/src/error.rs [hunk 1]
```diff
@@ -79,6 +79,9 @@ pub enum Error {
     #[error("Multiple transactions found: {0}")]
     MultipleTransactionsFound(Blake2bHash),
 
+    #[error("Invalid argument: {0}")]
+    InvalidArgument(String),
```
Comment (onmax) [inline rpc-server/src/error.rs:83]: @jsdanielh out  of curiosity.

Is there a way to change this line to accept `&str` so we then avoid the use of `to_string()`

Comment (hrxi) [reply rpc-server/src/error.rs:83]: You could change it to `&'static str`, but then it only works for string literals in the source code. Your current solution is more general.

**Review by nibhar — APPROVED** [review]

**Comment by jsdanielh** [comment]
Rebasing it to get it merged
