### PR TITLE
Consensus: fix history sync while processing received `BatchSetInfo`

### LINKED ISSUE #3206: History node fails to catch up
This is a **testnet** history node from tag v1.0.5 that was running fine until yesterday afternoon, block #5883215 @ 2024-12-17T11:39:30.248Z.

I don't have logs from the time it stalled, I only have logs from restart attempts later. I also only enabled DEBUG logging when restarting the next morning.

The stalled block is in epoch 67. The start election block of that epoch is #5883210 `fc138b56a2c4928057d5a209777cecc4b01ececc346c89d56bf2fba560f2278e`, this will be important later. My node obviously has this block and I can query it via RPC.

While attempting to restart this morning, while the network was still in epoch 67, I saw the same attempt to cluster sync, over and over, without any result, only increasing cluster IDs. Last I saw such a log message it was at ID 126 for the same cluster.

<details>
<summary><b>Restart logs within epoch 67</b></summary>

```
2024-12-18T07:58:28.133008670Z DEBUG sync_clustering      | Adding new cluster: SyncCluster {
    id: 54,
    first_epoch_number: 67,
    last_epoch_number: 67,
    num_epoch_ids: 1,
    num_peers: 1,
    num_pending_batch_sets: 0,
    num_epochs_finished: 0,
}
2024-12-18T07:58:28.133020990Z DEBUG sync_clustering      | Syncing cluster at index 0 of 1 clusters last_finalized_epoch=66 current_block=5883215 cluster=SyncCluster { id: 54, first_epoch_number: 67, last_epoch_number: 67, num_epoch_ids: 1, num_peers: 1, num_pending_batch_sets: 0, num_epochs_finished: 0 }
2024-12-18T07:58:28.139270550Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWQtB93NhbSGVEjyarwpABiyxef9ACJdob4ce1mzDgtg4h")
2024-12-18T07:58:28.139288910Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:28.139292260Z DEBUG sync_clustering      | Comparing with cluster #54: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:28.144727518Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWPwV3T3fwkavenKnWxT9e6wCvoQchok8X2YSRTB5WiLng")
2024-12-18T07:58:28.144764657Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:28.144767747Z DEBUG sync_clustering      | Comparing with cluster #54: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:28.148186404Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWPcinv5XbX7yjq9za1JoGWaEMsCETCm5AKYapfXRqevDs")
2024-12-18T07:58:28.148200184Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:28.148202964Z DEBUG sync_clustering      | Comparing with cluster #54: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:28.151991127Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWDUzhf8PZ3nBgNJCkyQzaCBCEFEemX5n8cbAgeBJ8dJag")
2024-12-18T07:58:28.152007837Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:28.152011617Z DEBUG sync_clustering      | Comparing with cluster #54: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:28.188171209Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWJQPzqURbkv7uH5BH476t73Wq5TB7H8oqx2Da6yFHJrDP")
2024-12-18T07:58:28.188193099Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:28.188196359Z DEBUG sync_clustering      | Comparing with cluster #54: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:28.339207135Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWDUUt3n39ecY2tznozgqUMkiMq8fy3B7qMrfu5x6JcGCm")
2024-12-18T07:58:28.339254145Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:28.339265805Z DEBUG sync_clustering      | Comparing with cluster #54: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:28.339702340Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWFEQSeVr9kaQyzCH9n1iBeJc1bBNDHfPvjuLKu8PJm6qA")
2024-12-18T07:58:28.339742030Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:28.339752309Z DEBUG sync_clustering      | Comparing with cluster #54: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:28.457603915Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWGLtJ7dchvSDV4JNT99QUzLpRdHGCGgVNyAXQyM21HXSV")
2024-12-18T07:58:28.457661594Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:28.457674464Z DEBUG sync_clustering      | Comparing with cluster #54: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:28.634375104Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWF4pZSd4wPcTqwhWVCBkV3T4qWdzdQSKpyHE342c64xeA")
2024-12-18T07:58:28.634469413Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:28.634480073Z DEBUG sync_clustering      | Comparing with cluster #54: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:28.698744884Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWK2poCu8McNHaYgDec8srq2bzoCjJkbJ1FXAEED32WJqg")
2024-12-18T07:58:28.698799073Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:28.698807033Z DEBUG sync_clustering      | Comparing with cluster #54: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:29.627782038Z INFO  cluster              | Syncing epoch #67/67 (2 checkpoints, 231048 total history items)
2024-12-18T07:58:29.627816728Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWB4jJPKn92N3G5TYCNZ2VAhJcVMQiz4x5xG8Q6XQRJ5QX
2024-12-18T07:58:29.627831678Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWQtB93NhbSGVEjyarwpABiyxef9ACJdob4ce1mzDgtg4h
2024-12-18T07:58:29.627839707Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWPwV3T3fwkavenKnWxT9e6wCvoQchok8X2YSRTB5WiLng
2024-12-18T07:58:29.627846257Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWPcinv5XbX7yjq9za1JoGWaEMsCETCm5AKYapfXRqevDs
2024-12-18T07:58:29.627851487Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWDUzhf8PZ3nBgNJCkyQzaCBCEFEemX5n8cbAgeBJ8dJag
2024-12-18T07:58:29.627857297Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWJQPzqURbkv7uH5BH476t73Wq5TB7H8oqx2Da6yFHJrDP
2024-12-18T07:58:29.627862447Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWDUUt3n39ecY2tznozgqUMkiMq8fy3B7qMrfu5x6JcGCm
2024-12-18T07:58:29.627867357Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWFEQSeVr9kaQyzCH9n1iBeJc1bBNDHfPvjuLKu8PJm6qA
2024-12-18T07:58:29.627873867Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWGLtJ7dchvSDV4JNT99QUzLpRdHGCGgVNyAXQyM21HXSV
2024-12-18T07:58:29.627879417Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWF4pZSd4wPcTqwhWVCBkV3T4qWdzdQSKpyHE342c64xeA
2024-12-18T07:58:29.627884697Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWK2poCu8McNHaYgDec8srq2bzoCjJkbJ1FXAEED32WJqg
2024-12-18T07:58:29.635654213Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWB4jJPKn92N3G5TYCNZ2VAhJcVMQiz4x5xG8Q6XQRJ5QX")
2024-12-18T07:58:29.635694922Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=false
2024-12-18T07:58:29.635717422Z DEBUG sync_clustering      | Adding new cluster: SyncCluster {
    id: 55,
    first_epoch_number: 67,
    last_epoch_number: 67,
    num_epoch_ids: 1,
    num_peers: 1,
    num_pending_batch_sets: 0,
    num_epochs_finished: 0,
}
2024-12-18T07:58:29.635750292Z DEBUG sync_clustering      | Syncing cluster at index 0 of 1 clusters last_finalized_epoch=66 current_block=5883215 cluster=SyncCluster { id: 55, first_epoch_number: 67, last_epoch_number: 67, num_epoch_ids: 1, num_peers: 1, num_pending_batch_sets: 0, num_epochs_finished: 0 }
2024-12-18T07:58:29.642896833Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWQtB93NhbSGVEjyarwpABiyxef9ACJdob4ce1mzDgtg4h")
2024-12-18T07:58:29.642922703Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:29.642926783Z DEBUG sync_clustering      | Comparing with cluster #55: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:29.644139961Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWDUzhf8PZ3nBgNJCkyQzaCBCEFEemX5n8cbAgeBJ8dJag")
2024-12-18T07:58:29.644159901Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:29.644165111Z DEBUG sync_clustering      | Comparing with cluster #55: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:29.648420379Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWPwV3T3fwkavenKnWxT9e6wCvoQchok8X2YSRTB5WiLng")
2024-12-18T07:58:29.648437659Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:29.648441079Z DEBUG sync_clustering      | Comparing with cluster #55: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:29.660262675Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWPcinv5XbX7yjq9za1JoGWaEMsCETCm5AKYapfXRqevDs")
2024-12-18T07:58:29.660282405Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:29.660286025Z DEBUG sync_clustering      | Comparing with cluster #55: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:29.691736523Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWJQPzqURbkv7uH5BH476t73Wq5TB7H8oqx2Da6yFHJrDP")
2024-12-18T07:58:29.691776603Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:29.691784433Z DEBUG sync_clustering      | Comparing with cluster #55: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:29.832331529Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWFEQSeVr9kaQyzCH9n1iBeJc1bBNDHfPvjuLKu8PJm6qA")
2024-12-18T07:58:29.832381538Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:29.832389518Z DEBUG sync_clustering      | Comparing with cluster #55: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:29.839048344Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWDUUt3n39ecY2tznozgqUMkiMq8fy3B7qMrfu5x6JcGCm")
2024-12-18T07:58:29.839086353Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:29.839101583Z DEBUG sync_clustering      | Comparing with cluster #55: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:29.962364446Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWGLtJ7dchvSDV4JNT99QUzLpRdHGCGgVNyAXQyM21HXSV")
2024-12-18T07:58:29.962420316Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:29.962431396Z DEBUG sync_clustering      | Comparing with cluster #55: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:30.139464222Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWF4pZSd4wPcTqwhWVCBkV3T4qWdzdQSKpyHE342c64xeA")
2024-12-18T07:58:30.139518992Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:30.139527651Z DEBUG sync_clustering      | Comparing with cluster #55: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:30.167478012Z DEBUG behaviour            | Failed to dial peer_id=12D3KooWRByyn3zHQeQmEcvtjyWxuN2fhwCWms1y5Ma5ehPUCc4D error="/ip4/172.18.0.9/tcp/8443/ws => Timeout has been reached"
2024-12-18T07:58:30.202880660Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWK2poCu8McNHaYgDec8srq2bzoCjJkbJ1FXAEED32WJqg")
2024-12-18T07:58:30.203042059Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:30.203061038Z DEBUG sync_clustering      | Comparing with cluster #55: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:30.999695570Z DEBUG behaviour            | Failed to dial peer_id=12D3KooWMAmvhahbehZysRvP8LZ43V3sEeMLojwQ1BMDWaW3CUpy error="/ip6/fe80::1123:721b:4670:a1c7/tcp/8443/ws => Invalid argument (os error 22), /ip4/192.168.10.46/tcp/8443/ws => Timeout has been reached"
2024-12-18T07:58:30.999941058Z DEBUG swarm                | Dialing peer peer_id=12D3KooWGFTi3ZnoF3YJv4eRxayvgp8X3rdZvZKepEnucbEAcLog
2024-12-18T07:58:31.006178939Z DEBUG behaviour            | Failed to dial peer peer_id=12D3KooWGFTi3ZnoF3YJv4eRxayvgp8X3rdZvZKepEnucbEAcLog error="Dial error: Unexpected peer ID 12D3KooWL4dWv7Ln5upnFKxSHosTBB2qKbpzBfP8USsL4ZAfygkS at Dialer { address: /ip4/46.4.159.118/tcp/8443/ws/p2p/12D3KooWGFTi3ZnoF3YJv4eRxayvgp8X3rdZvZKepEnucbEAcLog, role_override: Dialer, port_use: Reuse }."
2024-12-18T07:58:31.006498015Z DEBUG swarm                | Dialing peer peer_id=12D3KooWGocHoaK4F4T5qzehCmXC4LfX5HdBpyVESqSEYqLPrjdP
2024-12-18T07:58:31.011925592Z DEBUG behaviour            | Failed to dial peer peer_id=12D3KooWGocHoaK4F4T5qzehCmXC4LfX5HdBpyVESqSEYqLPrjdP error="Dial error: Unexpected peer ID 12D3KooWL4dWv7Ln5upnFKxSHosTBB2qKbpzBfP8USsL4ZAfygkS at Dialer { address: /ip4/46.4.159.118/tcp/8443/ws/p2p/12D3KooWGocHoaK4F4T5qzehCmXC4LfX5HdBpyVESqSEYqLPrjdP, role_override: Dialer, port_use: Reuse }."
2024-12-18T07:58:31.012167871Z DEBUG swarm                | Dialing peer peer_id=12D3KooWGocHoaK4F4T5qzehCmXC4LfX5HdBpyVESqSEYqLPrjdP
2024-12-18T07:58:31.017026124Z DEBUG behaviour            | Failed to dial peer peer_id=12D3KooWGocHoaK4F4T5qzehCmXC4LfX5HdBpyVESqSEYqLPrjdP error="Dial error: Unexpected peer ID 12D3KooWL4dWv7Ln5upnFKxSHosTBB2qKbpzBfP8USsL4ZAfygkS at Dialer { address: /ip4/46.4.159.118/tcp/8443/ws/p2p/12D3KooWGocHoaK4F4T5qzehCmXC4LfX5HdBpyVESqSEYqLPrjdP, role_override: Dialer, port_use: Reuse }."
2024-12-18T07:58:31.017265232Z DEBUG swarm                | Dialing peer peer_id=12D3KooWA7MYg6RpbCcZTReWBwcDQxWVXkxt9sBtJiCia3rzv6Za
2024-12-18T07:58:31.061042680Z DEBUG behaviour            | Failed to dial peer peer_id=12D3KooWA7MYg6RpbCcZTReWBwcDQxWVXkxt9sBtJiCia3rzv6Za error="Dial error: Unexpected peer ID 12D3KooWHtxprriWp7Gqh1drK3HqX9ffUepvPAriLeQouKEmTV8X at Dialer { address: /dns4/nimiq.surf/tcp/8443/wss/p2p/12D3KooWA7MYg6RpbCcZTReWBwcDQxWVXkxt9sBtJiCia3rzv6Za, role_override: Dialer, port_use: Reuse }."
2024-12-18T07:58:31.061639754Z DEBUG swarm                | Dialing peer peer_id=12D3KooWD4BY2kXBkFz8GeBrPmgF1jT8W2DsKEdbjtcz93nAPaX6
2024-12-18T07:58:31.079700301Z DEBUG behaviour            | Failed to dial peer peer_id=12D3KooWD4BY2kXBkFz8GeBrPmgF1jT8W2DsKEdbjtcz93nAPaX6 error="Dial error: Unexpected peer ID 12D3KooWQtB93NhbSGVEjyarwpABiyxef9ACJdob4ce1mzDgtg4h at Dialer { address: /ip4/89.58.58.210/tcp/28442/ws/p2p/12D3KooWD4BY2kXBkFz8GeBrPmgF1jT8W2DsKEdbjtcz93nAPaX6, role_override: Dialer, port_use: Reuse }."
2024-12-18T07:58:31.080045587Z DEBUG swarm                | Dialing peer peer_id=12D3KooWBDdqDEqL41tgWTTBacfPEq9HskZC3gAUeVHKfNWJLjjB
2024-12-18T07:58:31.097246431Z INFO  cluster              | Syncing epoch #67/67 (2 checkpoints, 231048 total history items)
2024-12-18T07:58:31.097274301Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWB4jJPKn92N3G5TYCNZ2VAhJcVMQiz4x5xG8Q6XQRJ5QX
2024-12-18T07:58:31.097286281Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWQtB93NhbSGVEjyarwpABiyxef9ACJdob4ce1mzDgtg4h
2024-12-18T07:58:31.097295221Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWDUzhf8PZ3nBgNJCkyQzaCBCEFEemX5n8cbAgeBJ8dJag
2024-12-18T07:58:31.097301731Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWPwV3T3fwkavenKnWxT9e6wCvoQchok8X2YSRTB5WiLng
2024-12-18T07:58:31.097307871Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWPcinv5XbX7yjq9za1JoGWaEMsCETCm5AKYapfXRqevDs
2024-12-18T07:58:31.097313161Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWJQPzqURbkv7uH5BH476t73Wq5TB7H8oqx2Da6yFHJrDP
2024-12-18T07:58:31.097318751Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWFEQSeVr9kaQyzCH9n1iBeJc1bBNDHfPvjuLKu8PJm6qA
2024-12-18T07:58:31.097324461Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWDUUt3n39ecY2tznozgqUMkiMq8fy3B7qMrfu5x6JcGCm
2024-12-18T07:58:31.097331060Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWGLtJ7dchvSDV4JNT99QUzLpRdHGCGgVNyAXQyM21HXSV
2024-12-18T07:58:31.097336290Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWF4pZSd4wPcTqwhWVCBkV3T4qWdzdQSKpyHE342c64xeA
2024-12-18T07:58:31.097341540Z DEBUG sync                 | Requesting epoch ids from peer peer_id=12D3KooWK2poCu8McNHaYgDec8srq2bzoCjJkbJ1FXAEED32WJqg
2024-12-18T07:58:31.104498951Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWB4jJPKn92N3G5TYCNZ2VAhJcVMQiz4x5xG8Q6XQRJ5QX")
2024-12-18T07:58:31.104621181Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=false
2024-12-18T07:58:31.104701840Z DEBUG sync_clustering      | Adding new cluster: SyncCluster {
    id: 56,
    first_epoch_number: 67,
    last_epoch_number: 67,
    num_epoch_ids: 1,
    num_peers: 1,
    num_pending_batch_sets: 0,
    num_epochs_finished: 0,
}
2024-12-18T07:58:31.104721450Z DEBUG sync_clustering      | Syncing cluster at index 0 of 1 clusters last_finalized_epoch=66 current_block=5883215 cluster=SyncCluster { id: 56, first_epoch_number: 67, last_epoch_number: 67, num_epoch_ids: 1, num_peers: 1, num_pending_batch_sets: 0, num_epochs_finished: 0 }
2024-12-18T07:58:31.115702234Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWQtB93NhbSGVEjyarwpABiyxef9ACJdob4ce1mzDgtg4h")
2024-12-18T07:58:31.115746994Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:31.115757294Z DEBUG sync_clustering      | Comparing with cluster #56: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:31.121462119Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWPwV3T3fwkavenKnWxT9e6wCvoQchok8X2YSRTB5WiLng")
2024-12-18T07:58:31.121582118Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:31.121604788Z DEBUG sync_clustering      | Comparing with cluster #56: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:31.121619418Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWPcinv5XbX7yjq9za1JoGWaEMsCETCm5AKYapfXRqevDs")
2024-12-18T07:58:31.121784496Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:31.121799096Z DEBUG sync_clustering      | Comparing with cluster #56: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:31.123679837Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWDUzhf8PZ3nBgNJCkyQzaCBCEFEemX5n8cbAgeBJ8dJag")
2024-12-18T07:58:31.123750617Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:31.123765357Z DEBUG sync_clustering      | Comparing with cluster #56: first_epoch_number=67, num_ids=1, match_until=1
2024-12-18T07:58:31.164049089Z DEBUG sync_clustering      | Received 1 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWJQPzqURbkv7uH5BH476t73Wq5TB7H8oqx2Da6yFHJrDP")
2024-12-18T07:58:31.164095259Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=1, num_clusters=0, active_cluster=true
2024-12-18T07:58:31.164105979Z DEBUG sync_clustering      | Comparing with cluster #56: first_epoch_number=67, num_ids=1, match_until=1
```
</details>

Coming back to it later, restarting again to see if that helps (it doesn't), the network is now in epoch 68. Now I get a different log and actual error message:

<details>
<summary><b>Restart logs within epoch 68</b></summary>

```
2024-12-18T15:25:30.313423416Z DEBUG sync_clustering      | Received 2 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWPcinv5XbX7yjq9za1JoGWaEMsCETCm5AKYapfXRqevDs")
2024-12-18T15:25:30.313500816Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=2, num_clusters=0, active_cluster=false
2024-12-18T15:25:30.313526126Z DEBUG sync_clustering      | Adding new cluster: SyncCluster {
    id: 0,
    first_epoch_number: 67,
    last_epoch_number: 68,
    num_epoch_ids: 2,
    num_peers: 1,
    num_pending_batch_sets: 0,
    num_epochs_finished: 0,
}
2024-12-18T15:25:30.313550835Z DEBUG sync_clustering      | Syncing cluster at index 0 of 1 clusters last_finalized_epoch=66 current_block=5883215 cluster=SyncCluster { id: 0, first_epoch_number: 67, last_epoch_number: 68, num_epoch_ids: 2, num_peers: 1, num_pending_batch_sets: 0, num_epochs_finished: 0 }

...

2024-12-18T15:25:32.037954596Z DEBUG swarm                | Saving peer peer_id=12D3KooWKd6cY4saxrTradfE5ELkxDFNWTC3Vn79H8ckNQDREA75 address=/dns4/faucet.pos.nimiq-testnet.com/tcp/8443/wss/p2p/12D3KooWKd6cY4saxrTradfE5ELkxDFNWTC3Vn79H8ckNQDREA75
2024-12-18T15:25:32.088946831Z DEBUG sync_clustering      | Received 2 epoch_ids starting at #67 (checkpoint=false) from PeerId("12D3KooWGLtJ7dchvSDV4JNT99QUzLpRdHGCGgVNyAXQyM21HXSV")
2024-12-18T15:25:32.089003610Z DEBUG sync_clustering      | Clustering ids: first_epoch_number=67, num_ids=2, num_clusters=0, active_cluster=true
2024-12-18T15:25:32.089014720Z DEBUG sync_clustering      | Comparing with cluster #0: first_epoch_number=67, num_ids=2, match_until=2
2024-12-18T15:25:32.166851973Z DEBUG syncer               | Incompatible peer is too far ahead peer_id=12D3KooWPQTqhoYUJjQjLx6KV9h8GX7cEg4MaeypMUDPnhf3R9yq peer_block_number=5984635 our_block_number=5883215 acceptance_window_size=120
2024-12-18T15:25:32.206910681Z DEBUG syncer               | Incompatible peer is too far ahead peer_id=12D3KooWNReUkzGUA2pEEWAxzacboaPeXqbHgnUg2WK33vsbA3rH peer_block_number=5984635 our_block_number=5883215 acceptance_window_size=120
2024-12-18T15:25:32.807581929Z DEBUG peer_contacts        | Adding peer contact peer_id=12D3KooWKd6cY4saxrTradfE5ELkxDFNWTC3Vn79H8ckNQDREA75 addresses=[/ip4/64.227.134.201/tcp/8444/ws, /dns4/faucet.pos.nimiq-testnet.com/tcp/8443/wss, /ip4/127.0.0.1/tcp/8443/wss, /ip4/127.0.0.1/tcp/8444/ws, /ip4/64.227.134.201/tcp/8443/wss, /ip4/64.227.134.201/tcp/8444/ws, /ip4/10.47.0.8/tcp/8443/wss, /ip4/10.47.0.8/tcp/8444/ws, /ip4/10.122.0.5/tcp/8443/wss, /ip4/10.122.0.5/tcp/8444/ws, /ip4/172.18.0.1/tcp/8443/wss, /ip4/172.18.0.1/tcp/8444/ws, /ip4/172.17.0.1/tcp/8443/wss, /ip4/172.17.0.1/tcp/8444/ws, /ip4/172.18.0.1/tcp/8444/ws]
2024-12-18T15:25:32.808189174Z INFO  swarm                | Peer joined peer_id=12D3KooWKd6cY4saxrTradfE5ELkxDFNWTC3Vn79H8ckNQDREA75 peer_address=/dns4/faucet.pos.nimiq-testnet.com/tcp/8443/wss/p2p/12D3KooWKd6cY4saxrTradfE5ELkxDFNWTC3Vn79H8ckNQDREA75
2024-12-18T15:25:32.808280304Z DEBUG syncer               | Macro sync returned incompatible peer peer_id=12D3KooWKd6cY4saxrTradfE5ELkxDFNWTC3Vn79H8ckNQDREA75
2024-12-18T15:25:32.808299813Z DEBUG syncer               | Checking if incompatible peer is in sync peer_id=12D3KooWKd6cY4saxrTradfE5ELkxDFNWTC3Vn79H8ckNQDREA75
2024-12-18T15:25:33.319083260Z DEBUG syncer               | Incompatible peer is too far ahead peer_id=12D3KooWKd6cY4saxrTradfE5ELkxDFNWTC3Vn79H8ckNQDREA75 peer_block_number=5984636 our_block_number=5883215 acceptance_window_size=120
2024-12-18T15:25:33.404905642Z DEBUG swarm                | Incoming connection connection_id=34 address=/ip4/172.19.0.13/tcp/55106/ws listen_address=/ip4/172.19.0.18/tcp/8443/ws
2024-12-18T15:25:33.729950130Z DEBUG swarm                | Incoming connection connection_id=35 address=/ip4/172.19.0.13/tcp/55116/ws listen_address=/ip4/172.19.0.18/tcp/8443/ws
2024-12-18T15:25:33.793984296Z INFO  cluster              | Syncing epoch #67/68 (2 checkpoints, 231048 total history items)
2024-12-18T15:25:33.932485942Z DEBUG swarm                | Connection established connection_id=34 peer_id=12D3KooWJR2abGXVY3Vczfkw8GeeUcnLdSjkR2RDueXvwh8BDDK6 address=/ip4/172.19.0.13/tcp/55106/ws direction="inbound" connections=1 established_in=527.405101ms
2024-12-18T15:25:33.938334738Z DEBUG swarm                | Incoming connection connection_id=36 address=/ip4/172.19.0.13/tcp/55128/ws listen_address=/ip4/172.19.0.18/tcp/8443/ws
2024-12-18T15:25:34.001332382Z INFO  cluster              | Syncing epoch #68/68 (2 checkpoints, 232445 total history items)
2024-12-18T15:25:34.001352842Z DEBUG cluster              | Adding pending batch set epoch=68 block=#5959230:MA:330e27533e history_len=176586 batch_set_index=0
2024-12-18T15:25:34.001374522Z DEBUG cluster              | Adding pending batch set epoch=68 block=#5969610:MA:fa140b7775 history_len=56317 batch_set_index=1
2024-12-18T15:25:34.052716024Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 1024/176586 (0.58%)
2024-12-18T15:25:34.060576296Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 2048/176586 (1.16%)
2024-12-18T15:25:34.060699635Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 3072/176586 (1.74%)
2024-12-18T15:25:34.060804424Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 4096/176586 (2.32%)
2024-12-18T15:25:34.060916103Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 5120/176586 (2.90%)
2024-12-18T15:25:34.143173511Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 6144/176586 (3.48%)

...

2024-12-18T15:25:41.522230582Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 163840/176586 (92.78%)
2024-12-18T15:25:41.649339742Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 164864/176586 (93.36%)
2024-12-18T15:25:41.649633050Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 165888/176586 (93.94%)
2024-12-18T15:25:41.649922548Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 166912/176586 (94.52%)
2024-12-18T15:25:41.650188555Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 167936/176586 (95.10%)
2024-12-18T15:25:41.650465563Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 168960/176586 (95.68%)
2024-12-18T15:25:41.650725452Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 169984/176586 (96.26%)
2024-12-18T15:25:41.650976930Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 171008/176586 (96.84%)
2024-12-18T15:25:41.651356067Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 172032/176586 (97.42%)
2024-12-18T15:25:41.651657464Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 173056/176586 (98.00%)
2024-12-18T15:25:41.732034607Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 174080/176586 (98.58%)
2024-12-18T15:25:41.732318166Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 175104/176586 (99.16%)
2024-12-18T15:25:42.139966838Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 176128/176586 (99.74%)
2024-12-18T15:25:42.140133356Z INFO  cluster              | Downloading history for epoch #68, batch set #0: 176586/176586 (100.00%)
2024-12-18T15:25:42.140191046Z INFO  cluster              | Downloading history for epoch #68, batch set #1: 1024/56317 (1.82%)
2024-12-18T15:25:42.140307836Z INFO  cluster              | Downloading history for epoch #68, batch set #1: 2048/56317 (3.64%)
2024-12-18T15:25:42.140616013Z INFO  cluster              | Downloading history for epoch #68, batch set #1: 3072/56317 (5.45%)
2024-12-18T15:25:42.140912281Z INFO  cluster              | Downloading history for epoch #68, batch set #1: 4096/56317 (7.27%)
2024-12-18T15:25:42.141212848Z INFO  cluster              | Downloading history for epoch #68, batch set #1: 5120/56317 (9.09%)
2024-12-18T15:25:42.141483577Z INFO  cluster              | Downloading history for epoch #68, batch set #1: 6144/56317 (10.91%)
2024-12-18T15:25:42.141734395Z INFO  cluster              | Downloading history for epoch #68, batch set #1: 7168/56317 (12.73%)
2024-12-18T15:25:42.147155244Z INFO  cluster              | Downloading history for epoch #68, batch set #1: 8192/56317 (14.55%)
2024-12-18T15:25:42.148951810Z INFO  cluster              | Downloading history for epoch #68, batch set #1: 9216/56317 (16.36%)
2024-12-18T15:25:42.149002360Z DEBUG sync_stream          | Processing epoch #68 (176586 history items)
2024-12-18T15:25:42.149429716Z WARN  block                | Rejecting block block=#5959230:MA:330e27533e parent_election_hash=c7b3799498f54d9762c31bc06e5afd88cd9ad4f156c21c3d6ed1e6b5cf04fd78 expected_parent_election_hash=fc138b56a2c4928057d5a209777cecc4b01ececc346c89d56bf2fba560f2278e reason="Wrong parent election hash"
2024-12-18T15:25:42.183039703Z WARN  sync_stream          | Failed to push epoch: InvalidBlock(InvalidParentElectionHash)
2024-12-18T15:25:42.183067963Z DEBUG sync_stream          | PushBatchSet from cluster_id 0 completed with result: Error
2024-12-18T15:25:42.183076222Z DEBUG sync_clustering      | Failed to push epoch from cluster 0: Error
2024-12-18T15:25:42.183083272Z DEBUG sync_clustering      | Closing connection to peer PeerId("12D3KooWPcinv5XbX7yjq9za1JoGWaEMsCETCm5AKYapfXRqevDs") after cluster 0 failed
2024-12-18T15:25:42.183094112Z DEBUG sync_clustering      | Closing connection to peer PeerId("12D3KooWQtB93NhbSGVEjyarwpABiyxef9ACJdob4ce1mzDgtg4h") after cluster 0 failed
2024-12-18T15:25:42.183102132Z DEBUG sync_clustering      | Closing connection to peer PeerId("12D3KooWB4jJPKn92N3G5TYCNZ2VAhJcVMQiz4x5xG8Q6XQRJ5QX") after cluster 0 failed
2024-12-18T15:25:42.183109362Z DEBUG sync_clustering      | Closing connection to peer PeerId("12D3KooWDUzhf8PZ3nBgNJCkyQzaCBCEFEemX5n8cbAgeBJ8dJag") after cluster 0 failed
2024-12-18T15:25:42.183115932Z DEBUG sync_clustering      | Closing connection to peer PeerId("12D3KooWPwV3T3fwkavenKnWxT9e6wCvoQchok8X2YSRTB5WiLng") after cluster 0 failed
2024-12-18T15:25:42.183162612Z DEBUG sync_clustering      | Closing connection to peer PeerId("12D3KooWJQPzqURbkv7uH5BH476t73Wq5TB7H8oqx2Da6yFHJrDP") after cluster 0 failed
2024-12-18T15:25:42.183177432Z DEBUG sync_clustering      | Closing connection to peer PeerId("12D3KooWF4pZSd4wPcTqwhWVCBkV3T4qWdzdQSKpyHE342c64xeA") after cluster 0 failed
2024-12-18T15:25:42.183191142Z DEBUG sync_clustering      | Closing connection to peer PeerId("12D3KooWDUUt3n39ecY2tznozgqUMkiMq8fy3B7qMrfu5x6JcGCm") after cluster 0 failed
2024-12-18T15:25:42.183201221Z DEBUG sync_clustering      | Closing connection to peer PeerId("12D3KooWK2poCu8McNHaYgDec8srq2bzoCjJkbJ1FXAEED32WJqg") after cluster 0 failed
2024-12-18T15:25:42.183210891Z DEBUG sync_clustering      | Closing connection to peer PeerId("12D3KooWGLtJ7dchvSDV4JNT99QUzLpRdHGCGgVNyAXQyM21HXSV") after cluster 0 failed
2024-12-18T15:25:42.183220371Z DEBUG sync_clustering      | Closing connection to peer PeerId("12D3KooWFEQSeVr9kaQyzCH9n1iBeJc1bBNDHfPvjuLKu8PJm6qA") after cluster 0 failed
```
</details>

The error message says it is trying to apply block #5959230, which is squarely in epoch 68 (the election block between epoch 67 and 68 is #5926410, **which my node doesn't yet have applied**). The application compares the new block's `parent_election_hash` to (probably) my node's current election head, which is still the one from the start of epoch 67, and fails with a mismatch.

Question is why is it trying to apply a block from epoch 68 (and not even the first macro block in that epoch) and suddenly finds that it forgot to apply all the remaining blocks in epoch 67, and why were they not applied in the first place?

### PR DESCRIPTION
**Pull request by Eligioo**
## What's in this pull request?
Determining the number of known transactions while processing received `BatchSetInfo`s, could result into crossing an epoch boundary. This would result into skipping the entire `BatchSetInfo` for the current epoch the node is in and prevent it from downloading new history chunks.

## Pull request checklist

- [x] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

File: consensus/src/sync/history/cluster.rs [hunk 1]
```diff
@@ -366,9 +366,15 @@ impl<TNetwork: Network + 'static> SyncCluster<TNetwork> {
         let current_epoch_number = blockchain.epoch_number();
         let num_known_txs = if epoch_number == current_epoch_number {
             let last_macro_block = Policy::last_macro_block(current_block_number);
-            blockchain
-                .history_store
-                .num_epoch_transactions_before(last_macro_block, None) as u64
+            // Check if Policy::last_macro_block crosses an epoch boundary. This could happen if locally the node is in the first batch of an epoch.
+            // In this case the number of transactions it knows must be 0.
+            if Policy::epoch_at(last_macro_block) != current_epoch_number {
```
Comment (sisou) [inline consensus/src/sync/history/cluster.rs]: I think you could use `Policy::is_election_block(last_macro_block)` here, too. It tests for the same.

**Review by jsdanielh — APPROVED** [review]
LGTM
