### PR TITLE
HistoryStore: fix `get_nonfinal_epoch_transactions()` returning incorrect results for batch 0

### LINKED ISSUE #2740: Panic in history sync
In [this CI run](https://github.com/nimiq/core-rs-albatross/actions/runs/9909303370/job/27377062039) a panic in history sync was observed:
```
2024-07-12T14:29:43.039376261Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Failed to find main chain predecessor while reverting blocks: BlockNotFound': blockchain/src/blockchain/history_sync.rs:566
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/capture.rs:422:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-panics-2.1.0/src/lib.rs:115:29
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
      std::panicking::rust_panic_with_hook
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:799:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:664:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
   5: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   6: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   7: core::result::unwrap_failed
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
   8: core::result::Result<T,E>::expect
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1034:23
   9: nimiq_blockchain::blockchain::history_sync::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::revert_blocks
             at /home/runner/work/core-rs-albatross/core-rs-albatross/blockchain/src/blockchain/history_sync.rs:564:29
  10: nimiq_blockchain::blockchain::history_sync::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::revert_to_common_state
             at /home/runner/work/core-rs-albatross/core-rs-albatross/blockchain/src/blockchain/history_sync.rs:517:17
  11: nimiq_blockchain::blockchain::history_sync::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::extend_history_sync
             at /home/runner/work/core-rs-albatross/core-rs-albatross/blockchain/src/blockchain/history_sync.rs:190:33
  12: nimiq_blockchain::blockchain::history_sync::<impl nimiq_blockchain::blockchain::blockchain::Blockchain>::push_history_sync
             at /home/runner/work/core-rs-albatross/core-rs-albatross/blockchain/src/blockchain/history_sync.rs:93:9
  13: nimiq_consensus::sync::history::sync_stream::<impl nimiq_consensus::sync::history::sync::HistoryMacroSync<TNetwork>>::poll_cluster::{{closure}}::{{closure}}
             at /home/runner/work/core-rs-albatross/core-rs-albatross/consensus/src/sync/history/sync_stream.rs:130:33
  14: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/blocking/task.rs:42:21
  15: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/core.rs:328:17
  16: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/loom/std/unsafe_cell.rs:16:9
      tokio::runtime::task::core::Core<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/core.rs:317:13
  17: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/harness.rs:485:19
  18: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic/unwind_safe.rs:272:9
  19: std::panicking::try::do_call
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  20: __rust_try
  21: std::panicking::try
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  22: std::panic::catch_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
  23: tokio::runtime::task::harness::poll_future
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/harness.rs:473:18
  24: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/harness.rs:208:27
  25: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/harness.rs:153:15
  26: tokio::runtime::task::raw::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/raw.rs:271:5
  27: tokio::runtime::task::raw::RawTask::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/raw.rs:201:18
  28: tokio::runtime::task::UnownedTask<S>::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/task/mod.rs:464:9
  29: tokio::runtime::blocking::pool::Task::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/blocking/pool.rs:159:9
  30: tokio::runtime::blocking::pool::Inner::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/blocking/pool.rs:513:17
  31: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/blocking/pool.rs:471:13
  32: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
  33: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/mod.rs:542:17
  34: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic/unwind_safe.rs:272:9
  35: std::panicking::try::do_call
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
  36: __rust_try
  37: std::panicking::try
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
  38: std::panic::catch_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
      std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/mod.rs:541:30
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  40: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2022:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2022:9
      std::sys::pal::unix::thread::Thread::new::thread_start
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys/pal/unix/thread.rs:108:17
  41: <unknown>
  42: <unknown>
```

### PR DESCRIPTION
**Pull request by styppo**
Refactor related functions and remove dead/duplicate code.

Closes #2740

### CODE REVIEW

File: blockchain/src/history/history_store.rs [hunk 1]
```diff
@@ -703,56 +691,30 @@ impl HistoryInterface for HistoryStore {
...
+            // If start != end, this is the last block that contained transactions.
+            let (start, end) = self.get_indexes_for_block(block_number, Some(txn));
+            if start != end {
+                break end as usize;
             }
-            end
-        };
-
-        end as usize
+            // If we switched epochs, start at 0.
```
Comment (jsdanielh) [inline blockchain/src/history/history_store.rs]: _start at 0_? Maybe:
```suggestion
            // If we switched epochs, this epoch is empty.
```

File: blockchain/src/history/history_store.rs [hunk 2]
```diff
@@ -703,56 +691,30 @@ impl HistoryInterface for HistoryStore {
...
+            if Policy::epoch_at(block_number) != epoch_number {
+                break 0;
+            }
+            // If we are at the genesis block, start at 0.
```
Comment (jsdanielh) [inline blockchain/src/history/history_store.rs]: _start at 0?_ Maybe:
```suggestion
            // If we are at the genesis block, this epoch is empty.
```
Although this looks like a hack because there are going to be transactions for blocks below the genesis

**Review by jsdanielh — APPROVED** [review]
