### PR TITLE
Fix signing of InStaking transaction with web-client's WASM API

### LINKED ISSUE #1879: Invalid Proof in WebClient Transaction::Sign
Signing InStaking transactions is broken in the webclient.

## Problem
Instead of returning the transaction the proof is set in place.
But not on both transactions

## Reproduce
Use the webclient to create a transaction using  
`Nimiq.TransactionBuilder.newCreateValidator`
then use `sign` on this transaction and try to   
send it using the `sendTransaction` of the client

## Change that introduced it
https://github.com/nimiq/core-rs-albatross/pull/1755

## The Code
https://github.com/nimiq/core-rs-albatross/blob/albatross/web-client/src/transaction.rs#L185-L199

### PR DESCRIPTION
**Pull request by sisou**
## What's in this pull request?

Fix signing of `InStaking` transactions with the web-client's WASM API.

## Pull request checklist

- [x] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

File: web-client/src/transaction.rs [hunk 1]
```diff
@@ -192,11 +192,14 @@ impl Transaction {
                 builder.sign_with_key_pair(key_pair.native_ref());
                 let mut builder = builder.generate().unwrap().unwrap_basic();
                 builder.sign_with_key_pair(key_pair.native_ref());
-                builder.generate().unwrap()
+                let tx = builder.generate().unwrap();
+                // Set the recipient data to the data with the added signature
+                self.set_recipient_data(tx.recipient_data);
```
Comment (sisou) [inline web-client/src/transaction.rs:197]: This is the relevant line that fixes the issue.

File: web-client/src/lib.rs [hunk 2]
```diff
@@ -8,3 +8,60 @@ mod client_configuration;
 mod primitives;
 mod transaction;
 mod utils;
+
+#[cfg(test)]
```
Comment (jsdanielh) [inline web-client/src/lib.rs:12]: I'd add a `mod test` and only gate the module behind the `test` feature:
```
#[cfg(test)]
mod tests {
  use wasm_bindgen::JsValue;
  use wasm_bindgen_test::wasm_bindgen_test;
...
  #[wasm_bindgen_test]
  pub fn it_can_create_and_sign_basic_transactions() {
...
}

Comment (sisou) [reply web-client/src/lib.rs:12]: Ah, that's how it works! I wanted to do that, but only tried opening braces.

Will do!

**Review by jsdanielh — APPROVED** [review]
