### PR TITLE
Fix `DoubleProposalProof`s

### LINKED ISSUE #2981: Double proposal proof signature verification generates the wrong data to be signed
This means that it's essentially impossible to generate double proposal proofs currently.

Currently, the double proposal proofs simply sign the Blake2**b** hash of the macro header, but the correct data can be seen in the following:

https://github.com/nimiq/core-rs-albatross/blob/76cc30b050c1273e1bef0e0915c8d99995c9000b/validator/src/tendermint.rs#L364-L378

### PR DESCRIPTION
**Pull request by hrxi**
They required data unrelated to the signed proposals. It now uses the same signing infrastructure by factoring it out to `TendermintProposal` in a common crate.

Fixes #2981.

### CODE REVIEW

File: primitives/block/src/equivocation_proof.rs [hunk 1]
```diff
@@ -405,13 +419,27 @@ impl DoubleProposalProof {
 
         if self.header1.block_number != self.header2.block_number
             || self.header1.round != self.header2.round
```
Comment (hrxi) [inline primitives/block/src/equivocation_proof.rs]: Is this check still correct or should it go away?

File: primitives/block/src/equivocation_proof.rs [hunk 2]
```diff
@@ -327,20 +331,30 @@ impl DoubleProposalProof {
     pub fn new(
         validator_address: Address,
         mut header1: MacroHeader,
+        mut round1: u32,
+        mut valid_round1: Option<u32>,
         mut justification1: SchnorrSignature,
         mut header2: MacroHeader,
+        mut round2: u32,
+        mut valid_round2: Option<u32>,
```
Comment (hrxi) [inline primitives/block/src/equivocation_proof.rs]: Should I merge the two `round` parameters into one, given that they have to be the same?

File: primitives/block/src/equivocation_proof.rs [hunk 3]
```diff
@@ -317,6 +317,10 @@ pub struct DoubleProposalProof {
     header1: MacroHeader,
     /// Header number 2.
     header2: MacroHeader,
+    round1: u32,
+    round2: u32,
+    valid_round1: Option<u32>,
+    valid_round2: Option<u32>,
```
Comment (nibhar) [inline primitives/block/src/equivocation_proof.rs]: I would prefer
```suggestion
    proposal1: TendermintProposal,
    /// Proposal number 2.
    proposal2: TendermintProposal,
```

File: primitives/block/src/equivocation_proof.rs (hunk 2 above)
Comment (nibhar) [reply primitives/block/src/equivocation_proof.rs]: I would prefer these be `TendermintProposal`, making the signature much smaller. If that turns out to be annoying or to require unnecessary cloning, then I think one round could be removed yes.

File: primitives/block/src/equivocation_proof.rs (hunk 1 above)
Comment (nibhar) [reply primitives/block/src/equivocation_proof.rs]: I would say this was not correct before and it should be removed. The round in the header only denotes when a proposal was created, not when it was proposed. Thus it should not be checked here.

**Review by nibhar — CHANGES_REQUESTED** [review]
Looks good to me outside of the `MacroHeader.round` check being incorrect (existed prior to this PR). So that should be removed. Other comments are purely cosmetic .

File: primitives/block/src/equivocation_proof.rs [hunk 4]
```diff
@@ -326,21 +326,21 @@ pub struct DoubleProposalProof {
...
+        mut proposal1: TendermintProposal<MacroHeader>,
         mut justification1: SchnorrSignature,
-        mut header2: MacroHeader,
+        mut proposal2: TendermintProposal<MacroHeader>,
         mut justification2: SchnorrSignature,
     ) -> DoubleProposalProof {
-        let hash1: Blake2bHash = header1.hash();
-        let hash2: Blake2bHash = header2.hash();
+        let hash1: Blake2bHash = proposal1.proposal.hash();
+        let hash2: Blake2bHash = proposal2.proposal.hash();
```
Comment (nibhar) [inline primitives/block/src/equivocation_proof.rs]: Maybe we should add an assert for the equal rounds here. Not strictly necessary but `DoubleProposalProof`s without matching rounds are invalid and should never be created.
```suggestion
        assert_eq!(proposal1.round, proposal2.round);
        let hash1: Blake2bHash = proposal1.proposal.hash();
        let hash2: Blake2bHash = proposal2.proposal.hash();
```

File: primitives/block/src/equivocation_proof.rs [hunk 5]
```diff
@@ -360,36 +360,36 @@ impl DoubleProposalProof {
...
 
     /// Verify the validity of a double proposal proof.
     pub fn verify_excluding_address_and_network(
         &self,
         signing_key: &SchnorrPublicKey,
     ) -> Result<(), EquivocationProofError> {
-        let hash1: Blake2bHash = self.header1.hash();
-        let hash2: Blake2bHash = self.header2.hash();
+        let hash1: Blake2bHash = self.proposal1.proposal.hash();
+        let hash2: Blake2bHash = self.proposal2.proposal.hash();
```
Comment (nibhar) [inline primitives/block/src/equivocation_proof.rs]: As far as I can see these are now only used for sorting. Sorting could also just use the Blake2sHash instead saving one hashing.

**Review by nibhar — APPROVED** [review]
LGTM. Left minor comments only.

File: primitives/block/src/equivocation_proof.rs (hunk 5 above)
Comment (hrxi) [reply primitives/block/src/equivocation_proof.rs]: Done.

File: primitives/block/src/equivocation_proof.rs (hunk 4 above)
Comment (hrxi) [reply primitives/block/src/equivocation_proof.rs]: Not done for now because we currently don't do that for the creation of any equivocation proof structure. We could automatically call `verify` I guess and `assert!` that it verifies. But maybe we could also do that at the call sites?

**Comment by hrxi** [comment]
Rebased for merging.
