### PR TITLE
Fix #1271

### LINKED ISSUE #1271: Panic in RPC server
In the latest devnet run, a panic coming from the RPC server was observed:

```
Jan 18 20:55:12 seed1 nimiq-client[104424]: 2023-01-18T20:55:12.956902Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'assertion failed: current_time >= genesis_time': primitives/src/policy.rs:289
Jan 18 20:55:12 seed1 nimiq-client[104424]:    0: <backtrace::capture::Backtrace as core::default::Default>::default
Jan 18 20:55:12 seed1 nimiq-client[104424]:    1: log_panics::Config::install_panic_hook::{{closure}}
Jan 18 20:55:12 seed1 nimiq-client[104424]:    2: std::panicking::rust_panic_with_hook
Jan 18 20:55:12 seed1 nimiq-client[104424]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/panicking.rs:702:17
Jan 18 20:55:12 seed1 nimiq-client[104424]:    3: std::panicking::begin_panic_handler::{{closure}}
Jan 18 20:55:12 seed1 nimiq-client[104424]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/panicking.rs:586:13
Jan 18 20:55:12 seed1 nimiq-client[104424]:    4: std::sys_common::backtrace::__rust_end_short_backtrace
Jan 18 20:55:12 seed1 nimiq-client[104424]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/sys_common/backtrace.rs:138:18
Jan 18 20:55:12 seed1 nimiq-client[104424]:    5: rust_begin_unwind
Jan 18 20:55:12 seed1 nimiq-client[104424]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/panicking.rs:584:5
Jan 18 20:55:12 seed1 nimiq-client[104424]:    6: core::panicking::panic_fmt
Jan 18 20:55:12 seed1 nimiq-client[104424]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/core/src/panicking.rs:142:14
Jan 18 20:55:12 seed1 nimiq-client[104424]:    7: core::panicking::panic
Jan 18 20:55:12 seed1 nimiq-client[104424]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/core/src/panicking.rs:48:5
Jan 18 20:55:12 seed1 nimiq-client[104424]:    8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:    9: <nimiq_rpc_server::dispatchers::policy::PolicyDispatcher as nimiq_jsonrpc_server::Dispatcher>::dispatch::{{closure}}
Jan 18 20:55:12 seed1 nimiq-client[104424]:   10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   16: <warp::filter::and_then::AndThenFuture<T,F> as core::future::future::Future>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   17: <warp::filter::or::EitherFuture<T,U> as core::future::future::Future>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   18: <warp::filter::and::AndFuture<T,U> as core::future::future::Future>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   19: warp::route::set
Jan 18 20:55:12 seed1 nimiq-client[104424]:   20: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
Jan 18 20:55:12 seed1 nimiq-client[104424]:   21: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
Jan 18 20:55:12 seed1 nimiq-client[104424]:   22: <hyper::server::server::new_svc::NewSvcTask<I,N,S,E,W> as core::future::future::Future>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   23: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Jan 18 20:55:12 seed1 nimiq-client[104424]:   24: tokio::runtime::task::core::Core<T,S>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   25: tokio::runtime::task::harness::Harness<T,S>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   26: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
Jan 18 20:55:12 seed1 nimiq-client[104424]:   27: tokio::runtime::scheduler::multi_thread::worker::Context::run
Jan 18 20:55:12 seed1 nimiq-client[104424]:   28: tokio::macros::scoped_tls::ScopedKey<T>::set
Jan 18 20:55:12 seed1 nimiq-client[104424]:   29: tokio::runtime::scheduler::multi_thread::worker::run
Jan 18 20:55:12 seed1 nimiq-client[104424]:   30: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Jan 18 20:55:12 seed1 nimiq-client[104424]:   31: tokio::runtime::task::core::Core<T,S>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   32: tokio::runtime::task::harness::Harness<T,S>::poll
Jan 18 20:55:12 seed1 nimiq-client[104424]:   33: std::sys_common::backtrace::__rust_begin_short_backtrace
Jan 18 20:55:12 seed1 nimiq-client[104424]:   34: core::ops::function::FnOnce::call_once{{vtable.shim}}
Jan 18 20:55:12 seed1 nimiq-client[104424]:   35: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jan 18 20:55:12 seed1 nimiq-client[104424]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/alloc/src/boxed.rs:1935:9
Jan 18 20:55:12 seed1 nimiq-client[104424]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Jan 18 20:55:12 seed1 nimiq-client[104424]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/alloc/src/boxed.rs:1935:9
Jan 18 20:55:12 seed1 nimiq-client[104424]:       std::sys::unix::thread::Thread::new::thread_start
Jan 18 20:55:12 seed1 nimiq-client[104424]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/sys/unix/thread.rs:108:17
Jan 18 20:55:12 seed1 nimiq-client[104424]:   36: <unknown>
Jan 18 20:55:12 seed1 nimiq-client[104424]:   37: <unknown>
```

### PR DESCRIPTION
**Pull request by viquezclaudio**
Fix panic in RPC server due to current_time >= genesis_time

...
## Pull request checklist

- [x] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

File: rpc-server/src/dispatchers/policy.rs [hunk 1]
```diff
@@ -183,6 +183,15 @@ impl PolicyInterface for PolicyDispatcher {
         genesis_time: u64,
         current_time: u64,
     ) -> RPCResult<u64, (), Self::Error> {
+        if genesis_time > current_time {
+            log::error!(
+                "The supplied current_time: {} must be equal or greater than the genesis_time {}",
+                current_time,
+                genesis_time
+            );
```
Comment (jsdanielh) [inline rpc-server/src/dispatchers/policy.rs]: Use `tracing` style
```suggestion
            log::error!(
                current_time,
                genesis_time,
                "The supplied time must be equal or greater than the genesis time"
            );
```

**Review by jsdanielh — CHANGES_REQUESTED** [review]

**Review by jsdanielh — APPROVED** [review]
