### PR TITLE
network-libp2p: Make peer and IP limits in the Connection Pool configurable

### LINKED ISSUE #2989: Peer Limit Configurations
Due to my network topology most peers are in the same subnet.

```

error=Listen error: Denied: connection denied
  | Max peer connections per IP subnet limit reached subnet_ip=10.42.7.0/24 limit=20
```

I would need these options configurable by the client.toml

https://github.com/nimiq/core-rs-albatross/blob/01f7d5e92b9a8ae1ddc916affd91484868fdc897/network-libp2p/src/connection_pool/behaviour.rs#L49-L54

### PR DESCRIPTION
**Pull request by Eligioo**
## What's in this pull request?
Make peer/IP limits in the Connection Pool behaviour configurable through the `client.toml`

## Pull request checklist

- [x] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

File: lib/src/config/config_file/mod.rs [hunk 1]
```diff
@@ -167,6 +167,13 @@ pub struct NetworkSettings {
     #[serde(default)]
     pub advertised_addresses: Option<Vec<String>>,
 
+    #[serde(default = "NetworkSettings::default_peer_count_max")]
+    pub peer_count_max: usize,
+    #[serde(default = "NetworkSettings::peer_count_per_ip_max")]
+    pub peer_count_per_ip_max: usize,
+    #[serde(default = "NetworkSettings::peer_count_per_ip_max")]
```
Comment (jsdanielh) [inline lib/src/config/config_file/mod.rs]: This is weird. I'd use another function for this field

File: lib/src/config/config_file/mod.rs [hunk 2]
```diff
@@ -167,6 +167,13 @@ pub struct NetworkSettings {
     #[serde(default)]
     pub advertised_addresses: Option<Vec<String>>,
 
+    #[serde(default = "NetworkSettings::default_peer_count_max")]
+    pub peer_count_max: usize,
```
Comment (jsdanielh) [inline lib/src/config/config_file/mod.rs:172]: Could you add some `rustdoc`?

File: lib/src/config/config_file/mod.rs [hunk 3]
```diff
@@ -167,6 +167,13 @@ pub struct NetworkSettings {
...
+    #[serde(default = "NetworkSettings::peer_count_per_ip_max")]
+    pub peer_count_per_ip_max: usize,
```
Comment (jsdanielh) [inline lib/src/config/config_file/mod.rs:175]: Could you add some `rustdoc`?

File: lib/src/config/config_file/mod.rs [hunk 4]
```diff
@@ -167,6 +167,13 @@ pub struct NetworkSettings {
...
+    #[serde(default = "NetworkSettings::peer_count_per_ip_max")]
+    pub peer_count_per_subnet_max: usize,
```
Comment (jsdanielh) [inline lib/src/config/config_file/mod.rs:178]: Could you add some `rustdoc`?

File: network-libp2p/src/config.rs [hunk 5]
```diff
@@ -31,6 +31,9 @@ pub struct Config {
     pub required_services: Services,
     pub tls: Option<TlsConfig>,
     pub desired_peer_count: usize,
+    pub peer_count_max: usize,
+    pub peer_count_per_ip_max: usize,
+    pub peer_count_per_subnet_max: usize,
```
Comment (jsdanielh) [inline network-libp2p/src/config.rs:40]: Could you add some `rustdoc`?

**Review by jsdanielh — APPROVED** [review]
