### PR TITLE
Moving zkprover proof generation logic to the poll function.

### LINKED ISSUE #1162: Panic in `zkp_prover`
In the latest devnet run a panic appeared in the prover node in `zkp_prover`:
```
Nov 30 10:38:16 prover1 nimiq-client[83122]: 2022-11-30T10:38:16.457688Z ERROR panic                | thread 'tokio-runtime-worker' panicked at 'The current state should never lag behind more than one epoch': core-rs-albatross/zkp-component/src/zkp_prover.rs:120
Nov 30 10:38:16 prover1 nimiq-client[83122]:    0: <backtrace::capture::Backtrace as core::default::Default>::default
Nov 30 10:38:16 prover1 nimiq-client[83122]:    1: log_panics::Config::install_panic_hook::{{closure}}
Nov 30 10:38:16 prover1 nimiq-client[83122]:    2: std::panicking::rust_panic_with_hook
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/panicking.rs:702:17
Nov 30 10:38:16 prover1 nimiq-client[83122]:    3: std::panicking::begin_panic_handler::{{closure}}
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/panicking.rs:586:13
Nov 30 10:38:16 prover1 nimiq-client[83122]:    4: std::sys_common::backtrace::__rust_end_short_backtrace
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/sys_common/backtrace.rs:138:18
Nov 30 10:38:16 prover1 nimiq-client[83122]:    5: rust_begin_unwind
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/panicking.rs:584:5
Nov 30 10:38:16 prover1 nimiq-client[83122]:    6: core::panicking::panic_fmt
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/core/src/panicking.rs:142:14
Nov 30 10:38:16 prover1 nimiq-client[83122]:    7: <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next
Nov 30 10:38:16 prover1 nimiq-client[83122]:    8: futures_util::stream::stream::StreamExt::poll_next_unpin
Nov 30 10:38:16 prover1 nimiq-client[83122]:    9: <nimiq_zkp_component::zkp_component::ZKPComponent<N> as core::future::future::Future>::poll
Nov 30 10:38:16 prover1 nimiq-client[83122]:   10: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Nov 30 10:38:16 prover1 nimiq-client[83122]:   11: tokio::runtime::task::core::Core<T,S>::poll
Nov 30 10:38:16 prover1 nimiq-client[83122]:   12: tokio::runtime::task::harness::Harness<T,S>::poll
Nov 30 10:38:16 prover1 nimiq-client[83122]:   13: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
Nov 30 10:38:16 prover1 nimiq-client[83122]:   14: tokio::runtime::scheduler::multi_thread::worker::Context::run
Nov 30 10:38:16 prover1 nimiq-client[83122]:   15: tokio::macros::scoped_tls::ScopedKey<T>::set
Nov 30 10:38:16 prover1 nimiq-client[83122]:   16: tokio::runtime::scheduler::multi_thread::worker::run
Nov 30 10:38:16 prover1 nimiq-client[83122]:   17: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
Nov 30 10:38:16 prover1 nimiq-client[83122]:   18: tokio::runtime::task::core::Core<T,S>::poll
Nov 30 10:38:16 prover1 nimiq-client[83122]:   19: tokio::runtime::task::harness::Harness<T,S>::poll
Nov 30 10:38:16 prover1 nimiq-client[83122]:   20: std::sys_common::backtrace::__rust_begin_short_backtrace
Nov 30 10:38:16 prover1 nimiq-client[83122]:   21: core::ops::function::FnOnce::call_once{{vtable.shim}}
Nov 30 10:38:16 prover1 nimiq-client[83122]:   22: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/alloc/src/boxed.rs:1935:9
Nov 30 10:38:16 prover1 nimiq-client[83122]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/alloc/src/boxed.rs:1935:9
Nov 30 10:38:16 prover1 nimiq-client[83122]:       std::sys::unix::thread::Thread::new::thread_start
Nov 30 10:38:16 prover1 nimiq-client[83122]:              at /rustc/affe0d3a00e92fa7885e3f5d2c5073fde432d154/library/std/src/sys/unix/thread.rs:108:17
Nov 30 10:38:16 prover1 nimiq-client[83122]:   23: <unknown>
Nov 30 10:38:16 prover1 nimiq-client[83122]:   24: <unknown>
Nov 30 10:38:16 prover1 nimiq-client[83122]:

```

### PR DESCRIPTION
**Pull request by paberr**
## What's in this pull request?

The ZKP prover would panic after producing one ZKP.
This would happen due to receiver lagging on the blockchain stream and the corresponding buffer being full.

We fixed it by keeping our own election block only buffer instead and moving some of the logic.

Also:
- fixes an issue with the path for the verifying keys in the blockchains,
- properly sets the `can_verify_history` flag, which previously caused issues on restarts of full nodes.

## Pull request checklist

- [x] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

**Review by viquezclaudio — APPROVED** [review]

File: zkp-component/src/zkp_prover.rs [hunk 1]
```diff
@@ -165,45 +134,102 @@ impl<N: Network> ZKProver<N> {
...
 impl<N: Network> Stream for ZKProver<N> {
     type Item = (ZKProof, MacroBlock);
 
     fn poll_next(mut self: Pin<&mut ZKProver<N>>, cx: &mut Context) -> Poll<Option<Self::Item>> {
+        // Fetch and store the new election blocks.
+        while let Poll::Ready(Some(block)) = self.election_stream.poll_next_unpin(cx) {
+            self.pending_election_blocks.push_back(block);
+        }
+
+        // Launches new proof generate, if we have a pending election block are and no proof generation is launched yet.
```
Comment (jsdanielh) [inline zkp-component/src/zkp_prover.rs]: Maybe:
```suggestion
        // Launches new proof generation, if we have a pending election block and no proof generation is launched yet.
```
?

File: zkp-component/src/zkp_prover.rs [hunk 2]
```diff
@@ -165,45 +134,102 @@ impl<N: Network> ZKProver<N> {
...
+                        *zkp_state_lock = new_zkp_state;
+
+                        let zkp_state_lock = RwLockWriteGuard::downgrade(zkp_state_lock);
+
+                        let proof: ZKProof = zkp_state_lock.clone().into();
+                        Self::broadcast_zk_proof(&self.network, proof.clone());
+                        return Poll::Ready(Some((proof, block)));
+                    }
+                    Err(e) => {
+                        log::error!("Error generating ZK Proof for block {}", e);
```
Comment (jsdanielh) [inline zkp-component/src/zkp_prover.rs]: I'd use tracing style for this
```suggestion
                        log::error!(error = e, "Error generating ZK Proof for block");
```

File: zkp-component/src/zkp_prover.rs [hunk 3]
```diff
@@ -165,45 +134,102 @@ impl<N: Network> ZKProver<N> {
...
+                .map(|res| res.map(|state| (state, block)))
+                .boxed(),
+            );
+            self.sender = Some(sender);
+        } else {
+            log::debug!(
+                "Won't generate zkp for a block of the past; block height: {}, current height: {}",
+                zkp_state.latest_block_number,
+                block.block_number()
+            );
```
Comment (jsdanielh) [inline zkp-component/src/zkp_prover.rs]: I'd use tracing style instead:
```suggestion
            log::debug!(
                block_height = zkp_state.latest_block_number,
                current_height = block.block_number(),
                "Won't generate zkp for a block of the past",
            );
```

**Review by jsdanielh — APPROVED** [review]
