### PR TITLE
Validity window fix

### LINKED ISSUE #1478: Start validator only when necessary data is available
Currently, the validator starts after consensus is established.
However, for full nodes, there are two further conditions that have to be met:
- History tree for the current epoch is extendable (currently equivalent to fully known)
- Transaction validity can be checked (currently equivalent to: we have the history tree over the last 7200 blocks)

While we could speed this up in the future by syncing the necessary data, we should at least wait until the conditions are met.

### LINKED ISSUE #1479: Macro sync only if necessary (full nodes)
The macro sync of full nodes always triggers a state sync.
In some cases, it might be wiser to run a history sync instead.
We should evaluate the threshold in the macro sync based on the number of leaves of the history (which can be proven by a hash).

- [ ] Decide when to live sync instead of macro sync? (To avoid syncing state) -> base on number of txs?
    - [ ] Alternative: fixed amount of macro blocks as threshold
    - [x] Include number of children in hash? Somehow include number of txs
    - [ ] history_root = Hash(num_leaves || peak_hash || root_hash)
    - [ ] We need a function prove_num_leaves() that returns num_leaves and peak_hash and root_hash

### PR DESCRIPTION
**Pull request by ii-cruz**
## What's in this pull request?
- Prepares SizeProof to be integrated into history sync
- Start validator only when conditions for validity window are fulfilled
- Optimize transition from macro to live sync for full nodes

## Pull request checklist

- [x] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

File: consensus/src/sync/light/sync_stream.rs [hunk 1]
```diff
@@ -66,11 +68,36 @@ impl<TNetwork: Network> LightMacroSync<TNetwork> {
...
-                            ),
+                            BlockchainProxy::Full(ref full_blockchain) => {
+                                let blockchain_urg = full_blockchain.upgradable_read();
+                                if block
+                                    .block_number()
+                                    .saturating_sub(blockchain_urg.block_number())
+                                    <= full_sync_threshold()
+                                {
+                                    // We deem this too close, thus we are not pushing the zkp.
+                                    // Instead we request the epoch ids from this peer.
```
Comment (nibhar) [inline consensus/src/sync/light/sync_stream.rs]: Please add a comment here explaining why not to push the zkp here, as even when pushing the zkp the epoch ids would still be requested  in lines 101+ of this file. The reason why this change set makes a difference is not immediately clear.

File: primitives/mmr/src/mmr/utils.rs [hunk 2]
```diff
@@ -31,6 +33,48 @@ pub(crate) fn bagging<H: Merge, I: Iterator<Item = Result<(H, usize), Error>>>(
     Ok(root)
 }
 
+/// Computes a size proof for an iterator over peak positions.
+/// This function fails if there is less than 2 peaks.
```
Comment (nibhar) [inline primitives/mmr/src/mmr/utils.rs]: Seems like it can prove a single Peek.

File: primitives/mmr/src/mmr/mod.rs [hunk 3]
```diff
@@ -143,6 +146,28 @@ impl<H: Merge + Clone, S: Store<H>> MerkleMountainRange<H, S> {
...
+        // Return the history root.
+        if self.is_empty() {
+            return Ok(SizeProof::EmptyTree);
+        }
+
+        let it = self.rev_peaks().map(|peak_pos| {
+            Ok((
+                self.store
+                    .get(peak_pos.index)
+                    .ok_or(Error::InconsistentStore)?,
```
Comment (nibhar) [inline primitives/mmr/src/mmr/mod.rs:163]: If I understand this correctly, adding a Single `Err` into the iterator will make the subsequent call to `prove_num_leaves` fail anyways. Maybe we can consider failing here already and returning `Err(Error::InconsistentStore)` without calling `prove_num_leaves`.

File: primitives/mmr/src/mmr/proof.rs [hunk 4]
```diff
@@ -6,6 +6,31 @@ use crate::mmr::peaks::PeakIterator;
 use crate::mmr::position::{leaf_number_to_index, Position};
 use crate::mmr::utils::bagging;
 
+#[derive(Clone, Debug)]
+pub enum SizeProof<H: Merge, T: Hash<H>> {
+    EmptyTree,
+    SingleItem(u64, T),
+    MultipleItem(u64, H, H),
```
Comment (nibhar) [inline primitives/mmr/src/mmr/proof.rs]:
```suggestion
    MultipleItems(u64, H, H),
```

File: validator/src/validator.rs [hunk 5]
```diff
@@ -432,8 +477,11 @@ where
     }
 
     fn on_blockchain_history_adopted(&mut self, _: &Blake2bHash) {
-        self.mempool.mempool_clean_up();
-        debug!("Performed a mempool clean up because new history was adopted");
+        // Mempool updates are only done once we can be active.
+        if self.can_be_active() {
```
Comment (nibhar) [inline validator/src/validator.rs:483]: Note on these:
As I understand it, the inconsistency of the mempool will subsequently fixed by #1475

File: validator/src/validator.rs [hunk 6]
```diff
@@ -816,11 +854,12 @@ where
...
-            let consensus_established = self.consensus.is_established();
-            trace!(?event, consensus_established, "blockchain event");
-            if consensus_established {
-                let latest_hash = event.get_newest_hash();
-                self.on_blockchain_event(event);
+            self.update_can_enforce_validity_window();
+            let can_be_active = self.can_be_active();
+            trace!(?event, can_be_active, "blockchain event");
+            let latest_hash = event.get_newest_hash();
+            self.on_blockchain_event(event);
```
Comment (nibhar) [inline validator/src/validator.rs:863]: It seems fine to me, but just to make sure:
This change executes `on_blockchain_event(event)` for every event, even when `!can_be_active`. Previously it would only execute with `consensus_established`. Is that by design?

Comment (ii-cruz) [reply validator/src/validator.rs:863]: It is yes

File: primitives/mmr/src/mmr/mod.rs (hunk 3 above)
Comment (paberr) [reply primitives/mmr/src/mmr/mod.rs:163]: This would only work if we first allocate it as a Vec (via collect).
However, that's not really needed. We thus only lazily evaluate that error.

**Review by jsdanielh — APPROVED** [review]
