### PR TITLE
Fix panic caused by corner case in mempool

### LINKED ISSUE #678: Panic during micro block production: Non existent address
Observed while testing some spammer enhancements in the single spammer/validator scenario.

```
 2022-03-14 15:35:03.915 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'Failed to compute accounts hash during block production: NonExistentAddress { address: Address("21616cdce8892004207ceb66d57ec258d1918d43") }': block-production/src/lib.rs:84
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: log_panics::init::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: _rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: nimiq_block_production::BlockProducer::next_micro_block
  10: nimiq_validator::micro::NextProduceMicroBlockEvent<TValidatorNetwork>::produce_micro_block
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: futures_util::stream::stream::StreamExt::poll_next_unpin
  13: <nimiq_validator::validator::Validator<TNetwork,TValidatorNetwork> as core::future::future::Future>::poll
  14: tokio::runtime::task::core::CoreStage<T>::poll
  15: std::panicking::try
  16: tokio::runtime::task::harness::poll_future
  17: tokio::runtime::task::harness::Harness<T,S>::poll
  18: std::thread::local::LocalKey<T>::with
  19: tokio::runtime::thread_pool::worker::Context::run_task
  20: tokio::runtime::thread_pool::worker::Context::run
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: tokio::runtime::thread_pool::worker::run
  23: tokio::runtime::task::harness::Harness<T,S>::poll
  24: tokio::runtime::blocking::pool::Inner::run
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: std::sys::unix::thread::Thread::new::thread_start
  28: __pthread_deallocate
```

### PR DESCRIPTION
**Pull request by viquezclaudio**
- When adopted blocks are recieved and mempool update is called, we need to handle the case
  where the transactions in the adopted blocks caused some sender to be pruned from the
  accounts tree, because in this particular case, we need to remove all the txns that
  belong to the pruned sender from the mempool
- Some unittests were added to reproduce the issue and verify the fix
- This fixes #678

### CODE REVIEW

File: mempool/src/mempool.rs [hunk 1]
```diff
@@ -277,6 +277,9 @@ impl Mempool {
                                         "There is no account for this sender in the blockchain {}",
                                         tx.sender.to_user_friendly_address()
                                     );
+                                    // The account from this sender was pruned/removed, so we need to delete all acounts that belong to this sender
```
Comment (sisou) [inline mempool/src/mempool.rs]:
```suggestion
                                    // The account from this sender was pruned/removed, so we need to delete all transactions sent from this address
```

File: mempool/src/mempool.rs [hunk 2]
```diff
@@ -690,6 +693,21 @@ impl MempoolState {
 
         Some(tx)
     }
+
+    // Removes all the transactions that belong to some specific sender
```
Comment (sisou) [inline mempool/src/mempool.rs]: This does not remove transactions _to_ the account, which I would say also _belong_ to it.
```suggestion
    // Removes all the transactions sent by some specific address
```

File: mempool/src/mempool.rs [hunk 3]
```diff
@@ -690,6 +693,21 @@ impl MempoolState {
...
+        for tx_hash in &self.state_by_sender.remove(sender_address).unwrap().txns {
+            self.best_transactions.remove(tx_hash);
+            self.worst_transactions.remove(tx_hash);
+            self.oldest_transactions.remove(tx_hash);
+
+            self.transactions.remove(tx_hash);
+        }
+
+        //Finally remove all the state associated with this sender
+        self.state_by_sender.remove(&sender_address);
```
Comment (sisou) [inline mempool/src/mempool.rs]: Isn't the state already removed above in line 700 when creating the loop range? Plus, there's a clippy warning on this line.

File: mempool/tests/mod.rs [hunk 4]
```diff
@@ -912,6 +914,318 @@ async fn mempool_update() {
...
+    log::debug!("Done generating transactions and accounts");
+
+    // Build a couple of blocks with adopted transactions
+    let num_txns = 10;
+    let mut adopted_transactions = vec![];
+    let recipient_balances = vec![0; num_txns as usize];
+
+    // Generate recipient accounts
+    let recipient_accounts = generate_accounts(recipient_balances, &mut genesis_builder, false);
+    // Use the same senders as before, because we want to test sender doesnt have enough funds to paid all pending txns
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]:
```suggestion
    // Use same senders as before, because we want to test that the sender doesn't have enough funds to pay all pending txns
```

File: mempool/src/mempool.rs [hunk 5]
```diff
@@ -690,6 +692,18 @@ impl MempoolState {
 
         Some(tx)
     }
+
+    //Removes all the transactions sent by some specific address
```
Comment (jsdanielh) [inline mempool/src/mempool.rs]:
```suggestion
    // Removes all the transactions sent by some specific address
```

File: mempool/tests/mod.rs [hunk 6]
```diff
@@ -912,6 +914,318 @@ async fn mempool_update() {
...
+            env.clone(),
+            time,
+            NetworkId::UnitAlbatross,
+            genesis_info.block,
+            genesis_info.accounts,
+        )
+        .unwrap(),
+    ));
+
+    // Create mempool and subscribe with a custom txn stream.
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]:
```suggestion
    // Create mempool and subscribe with a custom txn stream
```

File: mempool/tests/mod.rs [hunk 7]
```diff
@@ -912,6 +914,318 @@ async fn mempool_update() {
...
+    // Send txns to mempool
+    send_txn_to_mempool(&mempool, mock_network, mock_id, txns).await;
+
+    assert_eq!(
+        mempool.num_transactions(),
+        30,
+        "Number of txns in the mempools is not what is expected"
+    );
+
+    //We need a block producer to produce blocks
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]:
```suggestion
    // We need a block producer to produce blocks
```

File: mempool/tests/mod.rs [hunk 8]
```diff
@@ -912,6 +914,318 @@ async fn mempool_update() {
...
+
+    // Call mempool update
+    mempool.mempool_update(&adopted_micro_blocks[..], &[].to_vec());
+
+    // Get txns from mempool
+    let updated_txns = mempool.get_transactions_for_block(10_000);
+
+    // Expect only 20 transations because in the adopted blocks we included 10 txns that would cause the senders
+    // to not have enough balance to pay for all txns already in the mempool.
+
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]: Spare blank line

File: mempool/tests/mod.rs [hunk 9]
```diff
@@ -912,6 +914,318 @@ async fn mempool_update() {
...
+    }
+
+    // Call mempool update
+    mempool.mempool_update(&adopted_micro_blocks[..], &[].to_vec());
+
+    // Get txns from mempool
+    let updated_txns = mempool.get_transactions_for_block(10_000);
+
+    // Expect only 20 transations because in the adopted blocks we included 10 txns that would cause the senders
+    // to not have enough balance to pay for all txns already in the mempool.
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]:
```suggestion
    // to not have enough balance to pay for all txns already in the mempool
```

File: mempool/tests/mod.rs [hunk 10]
```diff
@@ -912,6 +914,318 @@ async fn mempool_update() {
...
+            &bc,
+            bc.time.now(),
+            0,
+            None,
+            vec![],
+            updated_txns.clone(),
+            vec![0x41],
+        );
+
+        //We should succeed producing a block with the remaining mempool transactions
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]:
```suggestion
        // We should succeed producing a block with the remaining mempool transactions
```

File: mempool/tests/mod.rs [hunk 11]
```diff
@@ -912,6 +914,318 @@ async fn mempool_update() {
...
+    log::debug!("Done generating transactions and accounts");
+
+    // Build a couple of blocks with adopted transactions
+    let num_txns = 10;
+    let mut adopted_transactions = vec![];
+    let recipient_balances = vec![0; num_txns as usize];
+
+    // Generate recipient accounts
+    let recipient_accounts = generate_accounts(recipient_balances, &mut genesis_builder, false);
+    // Use the same senders as before, because we want to test sender doesnt have enough funds to paid all pending txns
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]:
```suggestion
    // Use same senders as before, because we want to test that the sender doesn't have enough funds to pay all pending txns
```

File: mempool/tests/mod.rs [hunk 12]
```diff
@@ -912,6 +914,318 @@ async fn mempool_update() {
...
+    // Send txns to mempool
+    send_txn_to_mempool(&mempool, mock_network, mock_id, txns).await;
+
+    assert_eq!(
+        mempool.num_transactions(),
+        30,
+        "Number of txns in the mempools is not what is expected"
+    );
+
+    //We need a block producer to produce blocks
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]:
```suggestion
    // We need a block producer to produce blocks
```

File: mempool/tests/mod.rs [hunk 13]
```diff
@@ -912,6 +914,318 @@ async fn mempool_update() {
...
+            &bc,
+            bc.time.now(),
+            0,
+            None,
+            vec![],
+            updated_txns.clone(),
+            vec![0x41],
+        );
+
+        //We should succeed producing a block with the remaining mempool transactions
```
Comment (jsdanielh) [inline mempool/tests/mod.rs]:
```suggestion
        // We should succeed producing a block with the remaining mempool transactions
```

**Comment by viquezclaudio** [comment]
@jsdanielh changes applied

**Review by jsdanielh — APPROVED** [review]

**Comment by jsdanielh** [comment]
@viquezclaudio Also don't forget to sign the commits
