### PR TITLE
Fix panic caused by mempool executor

### LINKED ISSUE #516: Panic in mempool executor
During execution of devnet, the following panic was observed:

`Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:  2021-12-21 23:22:47.631 ERROR panic                | thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: AlreadySubscribed { topic_name: "transactions" }': /home/jeffrey/working_dir/nimiq/core-rs-albatross/mempool/src/executor.rs:60
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:    0: log_panics::init::{{closure}}
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:    1: std::panicking::rust_panic_with_hook
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:              at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/std/src/panicking.rs:610:17
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:    2: std::panicking::begin_panic_handler::{{closure}}
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:              at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/std/src/panicking.rs:502:13
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:              at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/std/src/sys_common/backtrace.rs:139:18
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:    4: rust_begin_unwind
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:              at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/std/src/panicking.rs:498:5
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:    5: core::panicking::panic_fmt
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:              at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/core/src/panicking.rs:107:14
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:    6: core::result::unwrap_failed
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:              at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/core/src/result.rs:1661:5
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:    7: tokio::runtime::task::harness::poll_future
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:    8: tokio::runtime::task::raw::poll
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:    9: tokio::runtime::thread_pool::worker::Context::run_task
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:   10: tokio::runtime::task::raw::poll
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:   11: std::sys_common::backtrace::__rust_begin_short_backtrace
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:   12: core::ops::function::FnOnce::call_once{{vtable.shim}}
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:   13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:              at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/alloc/src/boxed.rs:1811:9
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:              at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/alloc/src/boxed.rs:1811:9
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:       std::sys::unix::thread::Thread::new::thread_start
Dec 21 23:22:47 ip-172-31-12-149 nimiq-client[176076]:              at /rustc/91a0600a5c22b9d159e3c57526af83e71d1120f8/library/std/src/sys/unix/thread.rs:108:17
Dec 21 23:22:47 ip-172-3
[validator16.log](https://github.com/nimiq/core-rs-albatross/files/7764821/validator16.log)
1-12-149 nimiq-client[176076]:   14: start_thread
`

### PR DESCRIPTION
**Pull request by viquezclaudio**
Fixes #516
When the mempool executor was stopped, it was not being unsuscribed
from the network transaction topic, which is problematic after
it is restarted, since the network fails if we try to suscribe
and we are already suscribed.

Signed-off-by: viquezclaudio <viquezclaudio@gmail.com>

### CODE REVIEW

File: mempool/src/mempool.rs [hunk 1]
```diff
@@ -132,7 +147,28 @@ impl Mempool {
...
+        handle.take().expect("Expected an executor handle").abort();
+    }
+
+    /// Stops the mempool executor without TX stream
+    ///
+    /// This function is used for testing purposes (along with the start_executor_with_txn_stream function)
+    /// it is the responsability of the caller to suscribe and unsuscribe from the topic accordingly
+    ///
+    /// This functions should only be called only after one of the functions to start the executor is called.
+    pub async fn stop_executor_no_stream(&self) {
```
Comment (jsdanielh) [inline mempool/src/mempool.rs]: I'd change the pattern to:
`subscribe_start_executor` and `unsusbscribe_stop_executor`
and
`start_executor` and `stop_executor`
Or something similar

Comment (viquezclaudio) [reply mempool/src/mempool.rs]: I like `start_executor` and `stop_executor` for the ones that are used in the code
For the testing ones, I would prefer:
`start_executor_with_txn_stream` and `stop_executor_without_txn_stream`

Comment (jsdanielh) [reply mempool/src/mempool.rs]: Yeah, the one I'm not comfortable with is `stop_executor_without_txn_stream` since theoretically we do have at that point a `txn_stream`

Comment (viquezclaudio) [reply mempool/src/mempool.rs]: `stop_executor_without_unsuscribe` ?

Comment (jsdanielh) [reply mempool/src/mempool.rs]: Sounds better to me since we won't unsubscribe as the name implies

Comment (viquezclaudio) [reply mempool/src/mempool.rs]: done

**Review by jsdanielh — APPROVED** [review]
