### PR TITLE
network-libp2p: Allow the network to recover itself

### LINKED ISSUE #1337: Network does not recover after connection closed/errors
After several hours running the light client, standalone version, the following error occurred:
```
2023-02-09T21:53:03.07183Z ERROR connection           | 6d7737ef: socket error: decode error: i/o error: i/o error: Connection reset by peer (os error 54)    
2023-02-09T21:53:03.072394Z ERROR connection           | aa4faef3: socket error: decode error: i/o error: i/o error: Connection reset by peer (os error 54)    
2023-02-09T21:53:03.072907Z ERROR connection           | 1cbe2b78: socket error: decode error: i/o error: i/o error: Connection reset by peer (os error 54) 
```

After that consensus was lost, and the client never recovered. 
Full logs are attached
[light.log](https://github.com/nimiq/core-rs-albatross/files/10709443/light.log)

### PR DESCRIPTION
**Pull request by jsdanielh**
- Allow the network to recover itself
  - Allow the network to recover itself by resetting the peers and addresses marked as down when no connections nor dial attempts are being made.
  - Remove the restart functionality since now it is essentially the same as the `start_connecting` functionality.
  - Properly handle transport errors and mark the failed addresses as such in the connection pool behaviour.
  - Fix `TODO` in the connection pool related to not incrementing the dial attempt failures if the peer is already marked as down.
  - This fixes #1337.
- Re-introduce closing peer connections on ping failures. This was inadvertently removed in the latest `libp2p` upgrade since this is no longer performed by the `ping` behaviour.

## Pull request checklist

- [X] All tests pass. The project builds and runs.
- [X] I have resolved any merge conflicts.
- [X] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

File: network-libp2p/src/connection_pool/behaviour.rs [hunk 1]
```diff
@@ -29,23 +29,37 @@ use wasm_timer::Interval;
...
+    /// Number of peers connected per IP subnet
     ip_subnet_count: HashMap<IpNetwork, usize>,
+    /// Total peer count
     peer_count: usize,
 }
 
+/// Connection pool behaviour configuration
 #[derive(Clone, Debug)]
 struct Config {
+    /// Desires count of peers
```
Comment (hrxi) [inline network-libp2p/src/connection_pool/behaviour.rs]:
```suggestion
    /// Desired count of peers
```

File: network-libp2p/src/connection_pool/behaviour.rs [hunk 2]
```diff
@@ -29,23 +29,37 @@ use wasm_timer::Interval;
...
     peer_count_desired: usize,
+    /// Maximum count of peers
     peer_count_max: usize,
+    /// Maximum peer count per IP
     peer_count_per_ip_max: usize,
+    /// Maximum peer count per subnet
     peer_count_per_subnet_max: usize,
+    /// IPv4 subnet mask to apply to detect same connections for the same subnet
     ipv4_subnet_mask: u8,
```
Comment (hrxi) [inline network-libp2p/src/connection_pool/behaviour.rs]:
```suggestion
    ipv4_subnet_prefix_len: u8,
```
It's not really a mask.

File: network-libp2p/src/connection_pool/behaviour.rs [hunk 3]
```diff
@@ -29,23 +29,37 @@ use wasm_timer::Interval;
...
+    /// IPv6 subnet mask to apply to detect same connections for the same subnet
     ipv6_subnet_mask: u8,
```
Comment (hrxi) [inline network-libp2p/src/connection_pool/behaviour.rs]:
```suggestion
    ipv6_subnet_prefix_len: u8,
```

File: network-libp2p/src/connection_pool/behaviour.rs [hunk 4]
```diff
@@ -29,23 +29,37 @@ use wasm_timer::Interval;
...
+    /// Maximum number of peers that can be dialed simultaneously
```
Comment (hrxi) [inline network-libp2p/src/connection_pool/behaviour.rs]:
```suggestion
    /// Maximum number of peer dialings that can be in progress
```

File: network-libp2p/src/connection_pool/behaviour.rs [hunk 5]
```diff
@@ -74,6 +88,9 @@ impl Default for Config {
     }
 }
 
+/// State of all of the connections the network has like
```
Comment (hrxi) [inline network-libp2p/src/connection_pool/behaviour.rs]:
```suggestion
/// State of all of the connections the network has, like
```

**Review by hrxi — COMMENTED** [review]
Looks good, only comments for docs.

**Comment by jsdanielh** [comment]
> Looks good, only comments for docs.

Thanks for reviewing it. Just applied the suggestions.

**Review by viquezclaudio — APPROVED** [review]
