### PR TITLE
Poll again after adding new block stream

### LINKED ISSUE #2745: Failure to catch up through head requests
In [this CI run](https://github.com/nimiq/core-rs-albatross/actions/runs/9929244435/job/27426574778), it was observed that validators 2 and 4 fail to catch up after being restarted. It appears that unknown blocks received from head requests are not being pushed onto the chain, but only after the restart has occurred.

### PR DESCRIPTION
**Pull request by Eligioo**
## What's in this pull request?
With the PR #2702 the `BlockQueue` was moved into its own task so that it can be polled independently from the `Consensus`. This turned out to reveal a race against the `LiveSyncQueue` when adding a second stream to the `BlockQueue::block_stream`. This second stream is for example used when we want to push blocks received from `HeadRequests` into the `BlockQueue`. However since the `BlockQueue` now only is polled before the second stream got added, the second stream didn't get a chance to store a waker.

Before, when the BlockQueue was still part of the Consensus task, the BlockQueue would getting polled when the Consensus gets polled.

This PR fixes this by waking up the `BlockQueue` stream after a new stream to the `BlockQueue::block_stream` has been added.

## Pull request checklist

- [x] All tests pass. The project builds and runs.
- [x] I have resolved any merge conflicts.
- [x] I have resolved all `clippy` and `rustfmt` warnings.

### CODE REVIEW

**Review by nibhar — APPROVED** [review]
While I think this is a good change, as there could be a new stream being pushed into this select, the only place where I see it actually happening is in `LiveSyncer::with_queue`. That is a constructor, so I am not sure if the analysis of the race actually holds. I might be missing something here though.

**Comment by Eligioo** [comment]
@nibhar When the `BlockQueueProxy` is constructed, it also constructs a `BlockQueue` which is then immediately polled:
```
impl<N: Network> BlockQueueProxy<N> {
    pub async fn new(network: Arc<N>, blockchain: BlockchainProxy, config: QueueConfig) -> Self {
        let queue = BlockQueue::new(network, blockchain, config).await;
        Self::with_queue(queue)
    }
}
```

As part of the `BlockQueue` constructor, the `gossipsub` stream is added directly to the `block_stream`:
```
impl<N: Network> BlockQueue<N> {
    const MAX_BUFFERED_PER_PEER_PER_HEIGHT: usize = 5;

    pub async fn new(network: Arc<N>, blockchain: BlockchainProxy, config: QueueConfig) -> Self {
        let block_stream = if config.include_micro_bodies {
            network.subscribe::<BlockTopic>().await.unwrap().boxed()
        } else {
            network
                .subscribe::<BlockHeaderTopic>()
                .await
                .unwrap()
                .boxed()
        };

        Self::with_gossipsub_block_stream(blockchain, network, block_stream, config)
    }
}
```

Then when both are constructed, the `LiveSyncer::with_queue` is called which adds the second stream, that never gets polled, I was talking about.

**Review by styppo — APPROVED** [review]
LGTM 👍 

For completeness, let me mention that the root cause of the race is [the newly added `spawn()`](https://github.com/nimiq/core-rs-albatross/blob/albatross/consensus/src/sync/live/block_queue/proxy.rs#L75) in the `BlockQueueProxy` constructor, which causes the `BlockQueue`'s first `poll()` to race against the remaining `Consensus` initialization (in particular the `LiveSyncer` constructor which [adds the second block stream](https://github.com/nimiq/core-rs-albatross/blob/bc44e73833d59ba2049efd193fee1091574f672a/consensus/src/sync/live/mod.rs#L64)) that is executing on the original `Consensus` task.

File: consensus/src/sync/live/block_queue/queue.rs [hunk 1]
```diff
@@ -865,6 +869,8 @@ impl<N: Network> Stream for BlockQueue<N> {
     type Item = QueuedBlock<N>;
 
     fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context) -> Poll<Option<Self::Item>> {
+        self.waker.store_waker(cx);
```
Comment (hrxi) [inline consensus/src/sync/live/block_queue/queue.rs]: We only have to store the waker in the very bottom of this function, if we return `Poll::Pending`.

File: consensus/src/sync/live/block_queue/queue.rs [hunk 2]
```diff
@@ -79,6 +79,9 @@ pub struct BlockQueue<N: Network> {
     ///
     pending_requests:
         BTreeMap<u32, HashMap<Blake2bHash, OneshotSender<Result<Block, ResolveBlockError<N>>>>>,
+
+    /// Waker used for the poll function
+    pub(crate) waker: Option<Waker>,
```
Comment (ii-cruz) [inline consensus/src/sync/live/block_queue/queue.rs:84]: Perhaps add why we need the waker otherwise some other day we may think we no longer need it and fall into the same issue.

**Review by ii-cruz — APPROVED** [review]

File: consensus/src/sync/live/block_queue/queue.rs (hunk 2 above)
Comment (Eligioo) [reply consensus/src/sync/live/block_queue/queue.rs:84]: As the `waker` is now referenced in other parts of the codebase, I think it's enough that you shouldn't suddenly remove it without consequences.
